// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppSetting is the predicate function for appsetting builders.
type AppSetting func(*sql.Selector)

// CalendarEvent is the predicate function for calendarevent builders.
type CalendarEvent func(*sql.Selector)

// Conversation is the predicate function for conversation builders.
type Conversation func(*sql.Selector)

// EventProposal is the predicate function for eventproposal builders.
type EventProposal func(*sql.Selector)

// GoogleConnection is the predicate function for googleconnection builders.
type GoogleConnection func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)
