// Code generated by ent, DO NOT EDIT.

package googleconnection

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the googleconnection type in the database.
	Label = "google_connection"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRefreshToken holds the string denoting the refresh_token field in the database.
	FieldRefreshToken = "refresh_token"
	// FieldAccessToken holds the string denoting the access_token field in the database.
	FieldAccessToken = "access_token"
	// FieldTokenExpiry holds the string denoting the token_expiry field in the database.
	FieldTokenExpiry = "token_expiry"
	// FieldCalendarID holds the string denoting the calendar_id field in the database.
	FieldCalendarID = "calendar_id"
	// FieldConnected holds the string denoting the connected field in the database.
	FieldConnected = "connected"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the googleconnection in the database.
	Table = "google_connections"
)

// Columns holds all SQL columns for googleconnection fields.
var Columns = []string{
	FieldID,
	FieldRefreshToken,
	FieldAccessToken,
	FieldTokenExpiry,
	FieldCalendarID,
	FieldConnected,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRefreshToken holds the default value on creation for the "refresh_token" field.
	DefaultRefreshToken string
	// DefaultAccessToken holds the default value on creation for the "access_token" field.
	DefaultAccessToken string
	// DefaultCalendarID holds the default value on creation for the "calendar_id" field.
	DefaultCalendarID string
	// DefaultConnected holds the default value on creation for the "connected" field.
	DefaultConnected bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GoogleConnection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRefreshToken orders the results by the refresh_token field.
func ByRefreshToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshToken, opts...).ToFunc()
}

// ByAccessToken orders the results by the access_token field.
func ByAccessToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessToken, opts...).ToFunc()
}

// ByTokenExpiry orders the results by the token_expiry field.
func ByTokenExpiry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenExpiry, opts...).ToFunc()
}

// ByCalendarID orders the results by the calendar_id field.
func ByCalendarID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCalendarID, opts...).ToFunc()
}

// ByConnected orders the results by the connected field.
func ByConnected(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnected, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
