// Code generated by ent, DO NOT EDIT.

package googleconnection

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ITK13201/CalendarRabbit/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLTE(FieldID, id))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldRefreshToken, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldAccessToken, v))
}

// TokenExpiry applies equality check predicate on the "token_expiry" field. It's identical to TokenExpiryEQ.
func TokenExpiry(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldTokenExpiry, v))
}

// CalendarID applies equality check predicate on the "calendar_id" field. It's identical to CalendarIDEQ.
func CalendarID(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldCalendarID, v))
}

// Connected applies equality check predicate on the "connected" field. It's identical to ConnectedEQ.
func Connected(v bool) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldConnected, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldContainsFold(FieldRefreshToken, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldContainsFold(FieldAccessToken, v))
}

// TokenExpiryEQ applies the EQ predicate on the "token_expiry" field.
func TokenExpiryEQ(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldTokenExpiry, v))
}

// TokenExpiryNEQ applies the NEQ predicate on the "token_expiry" field.
func TokenExpiryNEQ(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNEQ(FieldTokenExpiry, v))
}

// TokenExpiryIn applies the In predicate on the "token_expiry" field.
func TokenExpiryIn(vs ...time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldIn(FieldTokenExpiry, vs...))
}

// TokenExpiryNotIn applies the NotIn predicate on the "token_expiry" field.
func TokenExpiryNotIn(vs ...time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNotIn(FieldTokenExpiry, vs...))
}

// TokenExpiryGT applies the GT predicate on the "token_expiry" field.
func TokenExpiryGT(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGT(FieldTokenExpiry, v))
}

// TokenExpiryGTE applies the GTE predicate on the "token_expiry" field.
func TokenExpiryGTE(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGTE(FieldTokenExpiry, v))
}

// TokenExpiryLT applies the LT predicate on the "token_expiry" field.
func TokenExpiryLT(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLT(FieldTokenExpiry, v))
}

// TokenExpiryLTE applies the LTE predicate on the "token_expiry" field.
func TokenExpiryLTE(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLTE(FieldTokenExpiry, v))
}

// TokenExpiryIsNil applies the IsNil predicate on the "token_expiry" field.
func TokenExpiryIsNil() predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldIsNull(FieldTokenExpiry))
}

// TokenExpiryNotNil applies the NotNil predicate on the "token_expiry" field.
func TokenExpiryNotNil() predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNotNull(FieldTokenExpiry))
}

// CalendarIDEQ applies the EQ predicate on the "calendar_id" field.
func CalendarIDEQ(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldCalendarID, v))
}

// CalendarIDNEQ applies the NEQ predicate on the "calendar_id" field.
func CalendarIDNEQ(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNEQ(FieldCalendarID, v))
}

// CalendarIDIn applies the In predicate on the "calendar_id" field.
func CalendarIDIn(vs ...string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldIn(FieldCalendarID, vs...))
}

// CalendarIDNotIn applies the NotIn predicate on the "calendar_id" field.
func CalendarIDNotIn(vs ...string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNotIn(FieldCalendarID, vs...))
}

// CalendarIDGT applies the GT predicate on the "calendar_id" field.
func CalendarIDGT(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGT(FieldCalendarID, v))
}

// CalendarIDGTE applies the GTE predicate on the "calendar_id" field.
func CalendarIDGTE(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGTE(FieldCalendarID, v))
}

// CalendarIDLT applies the LT predicate on the "calendar_id" field.
func CalendarIDLT(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLT(FieldCalendarID, v))
}

// CalendarIDLTE applies the LTE predicate on the "calendar_id" field.
func CalendarIDLTE(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLTE(FieldCalendarID, v))
}

// CalendarIDContains applies the Contains predicate on the "calendar_id" field.
func CalendarIDContains(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldContains(FieldCalendarID, v))
}

// CalendarIDHasPrefix applies the HasPrefix predicate on the "calendar_id" field.
func CalendarIDHasPrefix(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldHasPrefix(FieldCalendarID, v))
}

// CalendarIDHasSuffix applies the HasSuffix predicate on the "calendar_id" field.
func CalendarIDHasSuffix(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldHasSuffix(FieldCalendarID, v))
}

// CalendarIDEqualFold applies the EqualFold predicate on the "calendar_id" field.
func CalendarIDEqualFold(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEqualFold(FieldCalendarID, v))
}

// CalendarIDContainsFold applies the ContainsFold predicate on the "calendar_id" field.
func CalendarIDContainsFold(v string) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldContainsFold(FieldCalendarID, v))
}

// ConnectedEQ applies the EQ predicate on the "connected" field.
func ConnectedEQ(v bool) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldConnected, v))
}

// ConnectedNEQ applies the NEQ predicate on the "connected" field.
func ConnectedNEQ(v bool) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNEQ(FieldConnected, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GoogleConnection) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GoogleConnection) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GoogleConnection) predicate.GoogleConnection {
	return predicate.GoogleConnection(sql.NotPredicates(p))
}
