// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ITK13201/CalendarRabbit/backend/ent/appsetting"
)

// AppSetting is the model entity for the AppSetting schema.
type AppSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Timezone holds the value of the "timezone" field.
	Timezone string `json:"timezone,omitempty"`
	// LlmProvider holds the value of the "llm_provider" field.
	LlmProvider appsetting.LlmProvider `json:"llm_provider,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case appsetting.FieldID:
			values[i] = new(sql.NullInt64)
		case appsetting.FieldTimezone, appsetting.FieldLlmProvider:
			values[i] = new(sql.NullString)
		case appsetting.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppSetting fields.
func (_m *AppSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appsetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case appsetting.FieldTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timezone", values[i])
			} else if value.Valid {
				_m.Timezone = value.String
			}
		case appsetting.FieldLlmProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field llm_provider", values[i])
			} else if value.Valid {
				_m.LlmProvider = appsetting.LlmProvider(value.String)
			}
		case appsetting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AppSetting.
// This includes values selected through modifiers, order, etc.
func (_m *AppSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AppSetting.
// Note that you need to call AppSetting.Unwrap() before calling this method if this AppSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AppSetting) Update() *AppSettingUpdateOne {
	return NewAppSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AppSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AppSetting) Unwrap() *AppSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AppSetting) String() string {
	var builder strings.Builder
	builder.WriteString("AppSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("timezone=")
	builder.WriteString(_m.Timezone)
	builder.WriteString(", ")
	builder.WriteString("llm_provider=")
	builder.WriteString(fmt.Sprintf("%v", _m.LlmProvider))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AppSettings is a parsable slice of AppSetting.
type AppSettings []*AppSetting
