// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ITK13201/CalendarRabbit/backend/ent/calendarevent"
	"github.com/ITK13201/CalendarRabbit/backend/ent/eventproposal"
)

// CalendarEventCreate is the builder for creating a CalendarEvent entity.
type CalendarEventCreate struct {
	config
	mutation *CalendarEventMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *CalendarEventCreate) SetTitle(v string) *CalendarEventCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *CalendarEventCreate) SetStartsAt(v time.Time) *CalendarEventCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *CalendarEventCreate) SetEndsAt(v time.Time) *CalendarEventCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetAllDay sets the "all_day" field.
func (_c *CalendarEventCreate) SetAllDay(v bool) *CalendarEventCreate {
	_c.mutation.SetAllDay(v)
	return _c
}

// SetNillableAllDay sets the "all_day" field if the given value is not nil.
func (_c *CalendarEventCreate) SetNillableAllDay(v *bool) *CalendarEventCreate {
	if v != nil {
		_c.SetAllDay(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *CalendarEventCreate) SetLocation(v string) *CalendarEventCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *CalendarEventCreate) SetNillableLocation(v *string) *CalendarEventCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *CalendarEventCreate) SetDescription(v string) *CalendarEventCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CalendarEventCreate) SetNillableDescription(v *string) *CalendarEventCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *CalendarEventCreate) SetSourceURL(v string) *CalendarEventCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_c *CalendarEventCreate) SetNillableSourceURL(v *string) *CalendarEventCreate {
	if v != nil {
		_c.SetSourceURL(*v)
	}
	return _c
}

// SetGoogleEventID sets the "google_event_id" field.
func (_c *CalendarEventCreate) SetGoogleEventID(v string) *CalendarEventCreate {
	_c.mutation.SetGoogleEventID(v)
	return _c
}

// SetNillableGoogleEventID sets the "google_event_id" field if the given value is not nil.
func (_c *CalendarEventCreate) SetNillableGoogleEventID(v *string) *CalendarEventCreate {
	if v != nil {
		_c.SetGoogleEventID(*v)
	}
	return _c
}

// SetSyncPending sets the "sync_pending" field.
func (_c *CalendarEventCreate) SetSyncPending(v bool) *CalendarEventCreate {
	_c.mutation.SetSyncPending(v)
	return _c
}

// SetNillableSyncPending sets the "sync_pending" field if the given value is not nil.
func (_c *CalendarEventCreate) SetNillableSyncPending(v *bool) *CalendarEventCreate {
	if v != nil {
		_c.SetSyncPending(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CalendarEventCreate) SetCreatedAt(v time.Time) *CalendarEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CalendarEventCreate) SetNillableCreatedAt(v *time.Time) *CalendarEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CalendarEventCreate) SetUpdatedAt(v time.Time) *CalendarEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CalendarEventCreate) SetNillableUpdatedAt(v *time.Time) *CalendarEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddProposalIDs adds the "proposal" edge to the EventProposal entity by IDs.
func (_c *CalendarEventCreate) AddProposalIDs(ids ...int) *CalendarEventCreate {
	_c.mutation.AddProposalIDs(ids...)
	return _c
}

// AddProposal adds the "proposal" edges to the EventProposal entity.
func (_c *CalendarEventCreate) AddProposal(v ...*EventProposal) *CalendarEventCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProposalIDs(ids...)
}

// Mutation returns the CalendarEventMutation object of the builder.
func (_c *CalendarEventCreate) Mutation() *CalendarEventMutation {
	return _c.mutation
}

// Save creates the CalendarEvent in the database.
func (_c *CalendarEventCreate) Save(ctx context.Context) (*CalendarEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CalendarEventCreate) SaveX(ctx context.Context) *CalendarEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CalendarEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CalendarEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CalendarEventCreate) defaults() {
	if _, ok := _c.mutation.AllDay(); !ok {
		v := calendarevent.DefaultAllDay
		_c.mutation.SetAllDay(v)
	}
	if _, ok := _c.mutation.Location(); !ok {
		v := calendarevent.DefaultLocation
		_c.mutation.SetLocation(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := calendarevent.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.SourceURL(); !ok {
		v := calendarevent.DefaultSourceURL
		_c.mutation.SetSourceURL(v)
	}
	if _, ok := _c.mutation.GoogleEventID(); !ok {
		v := calendarevent.DefaultGoogleEventID
		_c.mutation.SetGoogleEventID(v)
	}
	if _, ok := _c.mutation.SyncPending(); !ok {
		v := calendarevent.DefaultSyncPending
		_c.mutation.SetSyncPending(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := calendarevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := calendarevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CalendarEventCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "CalendarEvent.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := calendarevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CalendarEvent.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "CalendarEvent.starts_at"`)}
	}
	if _, ok := _c.mutation.EndsAt(); !ok {
		return &ValidationError{Name: "ends_at", err: errors.New(`ent: missing required field "CalendarEvent.ends_at"`)}
	}
	if _, ok := _c.mutation.AllDay(); !ok {
		return &ValidationError{Name: "all_day", err: errors.New(`ent: missing required field "CalendarEvent.all_day"`)}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "CalendarEvent.location"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "CalendarEvent.description"`)}
	}
	if _, ok := _c.mutation.SourceURL(); !ok {
		return &ValidationError{Name: "source_url", err: errors.New(`ent: missing required field "CalendarEvent.source_url"`)}
	}
	if _, ok := _c.mutation.GoogleEventID(); !ok {
		return &ValidationError{Name: "google_event_id", err: errors.New(`ent: missing required field "CalendarEvent.google_event_id"`)}
	}
	if _, ok := _c.mutation.SyncPending(); !ok {
		return &ValidationError{Name: "sync_pending", err: errors.New(`ent: missing required field "CalendarEvent.sync_pending"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CalendarEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CalendarEvent.updated_at"`)}
	}
	return nil
}

func (_c *CalendarEventCreate) sqlSave(ctx context.Context) (*CalendarEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CalendarEventCreate) createSpec() (*CalendarEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &CalendarEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(calendarevent.Table, sqlgraph.NewFieldSpec(calendarevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(calendarevent.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(calendarevent.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(calendarevent.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = value
	}
	if value, ok := _c.mutation.AllDay(); ok {
		_spec.SetField(calendarevent.FieldAllDay, field.TypeBool, value)
		_node.AllDay = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(calendarevent.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(calendarevent.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(calendarevent.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.GoogleEventID(); ok {
		_spec.SetField(calendarevent.FieldGoogleEventID, field.TypeString, value)
		_node.GoogleEventID = value
	}
	if value, ok := _c.mutation.SyncPending(); ok {
		_spec.SetField(calendarevent.FieldSyncPending, field.TypeBool, value)
		_node.SyncPending = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(calendarevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(calendarevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProposalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   calendarevent.ProposalTable,
			Columns: []string{calendarevent.ProposalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventproposal.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CalendarEventCreateBulk is the builder for creating many CalendarEvent entities in bulk.
type CalendarEventCreateBulk struct {
	config
	err      error
	builders []*CalendarEventCreate
}

// Save creates the CalendarEvent entities in the database.
func (_c *CalendarEventCreateBulk) Save(ctx context.Context) ([]*CalendarEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CalendarEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CalendarEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CalendarEventCreateBulk) SaveX(ctx context.Context) []*CalendarEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CalendarEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CalendarEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
