// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ITK13201/CalendarRabbit/backend/ent/calendarevent"
)

// CalendarEvent is the model entity for the CalendarEvent schema.
type CalendarEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// EndsAt holds the value of the "ends_at" field.
	EndsAt time.Time `json:"ends_at,omitempty"`
	// AllDay holds the value of the "all_day" field.
	AllDay bool `json:"all_day,omitempty"`
	// Location holds the value of the "location" field.
	Location string `json:"location,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// SourceURL holds the value of the "source_url" field.
	SourceURL string `json:"source_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CalendarEventQuery when eager-loading is set.
	Edges        CalendarEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CalendarEventEdges holds the relations/edges for other nodes in the graph.
type CalendarEventEdges struct {
	// Proposal holds the value of the proposal edge.
	Proposal []*EventProposal `json:"proposal,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProposalOrErr returns the Proposal value or an error if the edge
// was not loaded in eager-loading.
func (e CalendarEventEdges) ProposalOrErr() ([]*EventProposal, error) {
	if e.loadedTypes[0] {
		return e.Proposal, nil
	}
	return nil, &NotLoadedError{edge: "proposal"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CalendarEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case calendarevent.FieldAllDay:
			values[i] = new(sql.NullBool)
		case calendarevent.FieldID:
			values[i] = new(sql.NullInt64)
		case calendarevent.FieldTitle, calendarevent.FieldLocation, calendarevent.FieldDescription, calendarevent.FieldSourceURL:
			values[i] = new(sql.NullString)
		case calendarevent.FieldStartsAt, calendarevent.FieldEndsAt, calendarevent.FieldCreatedAt, calendarevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CalendarEvent fields.
func (_m *CalendarEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case calendarevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case calendarevent.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case calendarevent.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case calendarevent.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = value.Time
			}
		case calendarevent.FieldAllDay:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field all_day", values[i])
			} else if value.Valid {
				_m.AllDay = value.Bool
			}
		case calendarevent.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				_m.Location = value.String
			}
		case calendarevent.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case calendarevent.FieldSourceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_url", values[i])
			} else if value.Valid {
				_m.SourceURL = value.String
			}
		case calendarevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case calendarevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CalendarEvent.
// This includes values selected through modifiers, order, etc.
func (_m *CalendarEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProposal queries the "proposal" edge of the CalendarEvent entity.
func (_m *CalendarEvent) QueryProposal() *EventProposalQuery {
	return NewCalendarEventClient(_m.config).QueryProposal(_m)
}

// Update returns a builder for updating this CalendarEvent.
// Note that you need to call CalendarEvent.Unwrap() before calling this method if this CalendarEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CalendarEvent) Update() *CalendarEventUpdateOne {
	return NewCalendarEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CalendarEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CalendarEvent) Unwrap() *CalendarEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CalendarEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CalendarEvent) String() string {
	var builder strings.Builder
	builder.WriteString("CalendarEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ends_at=")
	builder.WriteString(_m.EndsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("all_day=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllDay))
	builder.WriteString(", ")
	builder.WriteString("location=")
	builder.WriteString(_m.Location)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("source_url=")
	builder.WriteString(_m.SourceURL)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CalendarEvents is a parsable slice of CalendarEvent.
type CalendarEvents []*CalendarEvent
