// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ITK13201/CalendarRabbit/backend/ent/calendarevent"
	"github.com/ITK13201/CalendarRabbit/backend/ent/eventproposal"
	"github.com/ITK13201/CalendarRabbit/backend/ent/predicate"
)

// CalendarEventUpdate is the builder for updating CalendarEvent entities.
type CalendarEventUpdate struct {
	config
	hooks    []Hook
	mutation *CalendarEventMutation
}

// Where appends a list predicates to the CalendarEventUpdate builder.
func (_u *CalendarEventUpdate) Where(ps ...predicate.CalendarEvent) *CalendarEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *CalendarEventUpdate) SetTitle(v string) *CalendarEventUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CalendarEventUpdate) SetNillableTitle(v *string) *CalendarEventUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *CalendarEventUpdate) SetStartsAt(v time.Time) *CalendarEventUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *CalendarEventUpdate) SetNillableStartsAt(v *time.Time) *CalendarEventUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *CalendarEventUpdate) SetEndsAt(v time.Time) *CalendarEventUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *CalendarEventUpdate) SetNillableEndsAt(v *time.Time) *CalendarEventUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// SetAllDay sets the "all_day" field.
func (_u *CalendarEventUpdate) SetAllDay(v bool) *CalendarEventUpdate {
	_u.mutation.SetAllDay(v)
	return _u
}

// SetNillableAllDay sets the "all_day" field if the given value is not nil.
func (_u *CalendarEventUpdate) SetNillableAllDay(v *bool) *CalendarEventUpdate {
	if v != nil {
		_u.SetAllDay(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *CalendarEventUpdate) SetLocation(v string) *CalendarEventUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *CalendarEventUpdate) SetNillableLocation(v *string) *CalendarEventUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CalendarEventUpdate) SetDescription(v string) *CalendarEventUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CalendarEventUpdate) SetNillableDescription(v *string) *CalendarEventUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *CalendarEventUpdate) SetSourceURL(v string) *CalendarEventUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *CalendarEventUpdate) SetNillableSourceURL(v *string) *CalendarEventUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// SetGoogleEventID sets the "google_event_id" field.
func (_u *CalendarEventUpdate) SetGoogleEventID(v string) *CalendarEventUpdate {
	_u.mutation.SetGoogleEventID(v)
	return _u
}

// SetNillableGoogleEventID sets the "google_event_id" field if the given value is not nil.
func (_u *CalendarEventUpdate) SetNillableGoogleEventID(v *string) *CalendarEventUpdate {
	if v != nil {
		_u.SetGoogleEventID(*v)
	}
	return _u
}

// SetSyncPending sets the "sync_pending" field.
func (_u *CalendarEventUpdate) SetSyncPending(v bool) *CalendarEventUpdate {
	_u.mutation.SetSyncPending(v)
	return _u
}

// SetNillableSyncPending sets the "sync_pending" field if the given value is not nil.
func (_u *CalendarEventUpdate) SetNillableSyncPending(v *bool) *CalendarEventUpdate {
	if v != nil {
		_u.SetSyncPending(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CalendarEventUpdate) SetUpdatedAt(v time.Time) *CalendarEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddProposalIDs adds the "proposal" edge to the EventProposal entity by IDs.
func (_u *CalendarEventUpdate) AddProposalIDs(ids ...int) *CalendarEventUpdate {
	_u.mutation.AddProposalIDs(ids...)
	return _u
}

// AddProposal adds the "proposal" edges to the EventProposal entity.
func (_u *CalendarEventUpdate) AddProposal(v ...*EventProposal) *CalendarEventUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProposalIDs(ids...)
}

// Mutation returns the CalendarEventMutation object of the builder.
func (_u *CalendarEventUpdate) Mutation() *CalendarEventMutation {
	return _u.mutation
}

// ClearProposal clears all "proposal" edges to the EventProposal entity.
func (_u *CalendarEventUpdate) ClearProposal() *CalendarEventUpdate {
	_u.mutation.ClearProposal()
	return _u
}

// RemoveProposalIDs removes the "proposal" edge to EventProposal entities by IDs.
func (_u *CalendarEventUpdate) RemoveProposalIDs(ids ...int) *CalendarEventUpdate {
	_u.mutation.RemoveProposalIDs(ids...)
	return _u
}

// RemoveProposal removes "proposal" edges to EventProposal entities.
func (_u *CalendarEventUpdate) RemoveProposal(v ...*EventProposal) *CalendarEventUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProposalIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CalendarEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CalendarEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CalendarEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CalendarEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CalendarEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := calendarevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CalendarEventUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := calendarevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CalendarEvent.title": %w`, err)}
		}
	}
	return nil
}

func (_u *CalendarEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(calendarevent.Table, calendarevent.Columns, sqlgraph.NewFieldSpec(calendarevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(calendarevent.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(calendarevent.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(calendarevent.FieldEndsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AllDay(); ok {
		_spec.SetField(calendarevent.FieldAllDay, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(calendarevent.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(calendarevent.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(calendarevent.FieldSourceURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoogleEventID(); ok {
		_spec.SetField(calendarevent.FieldGoogleEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncPending(); ok {
		_spec.SetField(calendarevent.FieldSyncPending, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(calendarevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProposalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   calendarevent.ProposalTable,
			Columns: []string{calendarevent.ProposalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventproposal.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProposalIDs(); len(nodes) > 0 && !_u.mutation.ProposalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   calendarevent.ProposalTable,
			Columns: []string{calendarevent.ProposalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventproposal.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProposalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   calendarevent.ProposalTable,
			Columns: []string{calendarevent.ProposalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventproposal.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{calendarevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CalendarEventUpdateOne is the builder for updating a single CalendarEvent entity.
type CalendarEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CalendarEventMutation
}

// SetTitle sets the "title" field.
func (_u *CalendarEventUpdateOne) SetTitle(v string) *CalendarEventUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CalendarEventUpdateOne) SetNillableTitle(v *string) *CalendarEventUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *CalendarEventUpdateOne) SetStartsAt(v time.Time) *CalendarEventUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *CalendarEventUpdateOne) SetNillableStartsAt(v *time.Time) *CalendarEventUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *CalendarEventUpdateOne) SetEndsAt(v time.Time) *CalendarEventUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *CalendarEventUpdateOne) SetNillableEndsAt(v *time.Time) *CalendarEventUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// SetAllDay sets the "all_day" field.
func (_u *CalendarEventUpdateOne) SetAllDay(v bool) *CalendarEventUpdateOne {
	_u.mutation.SetAllDay(v)
	return _u
}

// SetNillableAllDay sets the "all_day" field if the given value is not nil.
func (_u *CalendarEventUpdateOne) SetNillableAllDay(v *bool) *CalendarEventUpdateOne {
	if v != nil {
		_u.SetAllDay(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *CalendarEventUpdateOne) SetLocation(v string) *CalendarEventUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *CalendarEventUpdateOne) SetNillableLocation(v *string) *CalendarEventUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CalendarEventUpdateOne) SetDescription(v string) *CalendarEventUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CalendarEventUpdateOne) SetNillableDescription(v *string) *CalendarEventUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *CalendarEventUpdateOne) SetSourceURL(v string) *CalendarEventUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *CalendarEventUpdateOne) SetNillableSourceURL(v *string) *CalendarEventUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// SetGoogleEventID sets the "google_event_id" field.
func (_u *CalendarEventUpdateOne) SetGoogleEventID(v string) *CalendarEventUpdateOne {
	_u.mutation.SetGoogleEventID(v)
	return _u
}

// SetNillableGoogleEventID sets the "google_event_id" field if the given value is not nil.
func (_u *CalendarEventUpdateOne) SetNillableGoogleEventID(v *string) *CalendarEventUpdateOne {
	if v != nil {
		_u.SetGoogleEventID(*v)
	}
	return _u
}

// SetSyncPending sets the "sync_pending" field.
func (_u *CalendarEventUpdateOne) SetSyncPending(v bool) *CalendarEventUpdateOne {
	_u.mutation.SetSyncPending(v)
	return _u
}

// SetNillableSyncPending sets the "sync_pending" field if the given value is not nil.
func (_u *CalendarEventUpdateOne) SetNillableSyncPending(v *bool) *CalendarEventUpdateOne {
	if v != nil {
		_u.SetSyncPending(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CalendarEventUpdateOne) SetUpdatedAt(v time.Time) *CalendarEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddProposalIDs adds the "proposal" edge to the EventProposal entity by IDs.
func (_u *CalendarEventUpdateOne) AddProposalIDs(ids ...int) *CalendarEventUpdateOne {
	_u.mutation.AddProposalIDs(ids...)
	return _u
}

// AddProposal adds the "proposal" edges to the EventProposal entity.
func (_u *CalendarEventUpdateOne) AddProposal(v ...*EventProposal) *CalendarEventUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProposalIDs(ids...)
}

// Mutation returns the CalendarEventMutation object of the builder.
func (_u *CalendarEventUpdateOne) Mutation() *CalendarEventMutation {
	return _u.mutation
}

// ClearProposal clears all "proposal" edges to the EventProposal entity.
func (_u *CalendarEventUpdateOne) ClearProposal() *CalendarEventUpdateOne {
	_u.mutation.ClearProposal()
	return _u
}

// RemoveProposalIDs removes the "proposal" edge to EventProposal entities by IDs.
func (_u *CalendarEventUpdateOne) RemoveProposalIDs(ids ...int) *CalendarEventUpdateOne {
	_u.mutation.RemoveProposalIDs(ids...)
	return _u
}

// RemoveProposal removes "proposal" edges to EventProposal entities.
func (_u *CalendarEventUpdateOne) RemoveProposal(v ...*EventProposal) *CalendarEventUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProposalIDs(ids...)
}

// Where appends a list predicates to the CalendarEventUpdate builder.
func (_u *CalendarEventUpdateOne) Where(ps ...predicate.CalendarEvent) *CalendarEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CalendarEventUpdateOne) Select(field string, fields ...string) *CalendarEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CalendarEvent entity.
func (_u *CalendarEventUpdateOne) Save(ctx context.Context) (*CalendarEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CalendarEventUpdateOne) SaveX(ctx context.Context) *CalendarEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CalendarEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CalendarEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CalendarEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := calendarevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CalendarEventUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := calendarevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CalendarEvent.title": %w`, err)}
		}
	}
	return nil
}

func (_u *CalendarEventUpdateOne) sqlSave(ctx context.Context) (_node *CalendarEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(calendarevent.Table, calendarevent.Columns, sqlgraph.NewFieldSpec(calendarevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CalendarEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, calendarevent.FieldID)
		for _, f := range fields {
			if !calendarevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != calendarevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(calendarevent.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(calendarevent.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(calendarevent.FieldEndsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AllDay(); ok {
		_spec.SetField(calendarevent.FieldAllDay, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(calendarevent.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(calendarevent.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(calendarevent.FieldSourceURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoogleEventID(); ok {
		_spec.SetField(calendarevent.FieldGoogleEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncPending(); ok {
		_spec.SetField(calendarevent.FieldSyncPending, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(calendarevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProposalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   calendarevent.ProposalTable,
			Columns: []string{calendarevent.ProposalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventproposal.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProposalIDs(); len(nodes) > 0 && !_u.mutation.ProposalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   calendarevent.ProposalTable,
			Columns: []string{calendarevent.ProposalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventproposal.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProposalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   calendarevent.ProposalTable,
			Columns: []string{calendarevent.ProposalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventproposal.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CalendarEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{calendarevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
