// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/ITK13201/CalendarRabbit/backend/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ITK13201/CalendarRabbit/backend/ent/appsetting"
	"github.com/ITK13201/CalendarRabbit/backend/ent/calendarevent"
	"github.com/ITK13201/CalendarRabbit/backend/ent/conversation"
	"github.com/ITK13201/CalendarRabbit/backend/ent/eventproposal"
	"github.com/ITK13201/CalendarRabbit/backend/ent/message"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AppSetting is the client for interacting with the AppSetting builders.
	AppSetting *AppSettingClient
	// CalendarEvent is the client for interacting with the CalendarEvent builders.
	CalendarEvent *CalendarEventClient
	// Conversation is the client for interacting with the Conversation builders.
	Conversation *ConversationClient
	// EventProposal is the client for interacting with the EventProposal builders.
	EventProposal *EventProposalClient
	// Message is the client for interacting with the Message builders.
	Message *MessageClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AppSetting = NewAppSettingClient(c.config)
	c.CalendarEvent = NewCalendarEventClient(c.config)
	c.Conversation = NewConversationClient(c.config)
	c.EventProposal = NewEventProposalClient(c.config)
	c.Message = NewMessageClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		AppSetting:    NewAppSettingClient(cfg),
		CalendarEvent: NewCalendarEventClient(cfg),
		Conversation:  NewConversationClient(cfg),
		EventProposal: NewEventProposalClient(cfg),
		Message:       NewMessageClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		AppSetting:    NewAppSettingClient(cfg),
		CalendarEvent: NewCalendarEventClient(cfg),
		Conversation:  NewConversationClient(cfg),
		EventProposal: NewEventProposalClient(cfg),
		Message:       NewMessageClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AppSetting.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AppSetting.Use(hooks...)
	c.CalendarEvent.Use(hooks...)
	c.Conversation.Use(hooks...)
	c.EventProposal.Use(hooks...)
	c.Message.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.AppSetting.Intercept(interceptors...)
	c.CalendarEvent.Intercept(interceptors...)
	c.Conversation.Intercept(interceptors...)
	c.EventProposal.Intercept(interceptors...)
	c.Message.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AppSettingMutation:
		return c.AppSetting.mutate(ctx, m)
	case *CalendarEventMutation:
		return c.CalendarEvent.mutate(ctx, m)
	case *ConversationMutation:
		return c.Conversation.mutate(ctx, m)
	case *EventProposalMutation:
		return c.EventProposal.mutate(ctx, m)
	case *MessageMutation:
		return c.Message.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AppSettingClient is a client for the AppSetting schema.
type AppSettingClient struct {
	config
}

// NewAppSettingClient returns a client for the AppSetting from the given config.
func NewAppSettingClient(c config) *AppSettingClient {
	return &AppSettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appsetting.Hooks(f(g(h())))`.
func (c *AppSettingClient) Use(hooks ...Hook) {
	c.hooks.AppSetting = append(c.hooks.AppSetting, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `appsetting.Intercept(f(g(h())))`.
func (c *AppSettingClient) Intercept(interceptors ...Interceptor) {
	c.inters.AppSetting = append(c.inters.AppSetting, interceptors...)
}

// Create returns a builder for creating a AppSetting entity.
func (c *AppSettingClient) Create() *AppSettingCreate {
	mutation := newAppSettingMutation(c.config, OpCreate)
	return &AppSettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppSetting entities.
func (c *AppSettingClient) CreateBulk(builders ...*AppSettingCreate) *AppSettingCreateBulk {
	return &AppSettingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AppSettingClient) MapCreateBulk(slice any, setFunc func(*AppSettingCreate, int)) *AppSettingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AppSettingCreateBulk{err: fmt.Errorf("calling to AppSettingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AppSettingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AppSettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppSetting.
func (c *AppSettingClient) Update() *AppSettingUpdate {
	mutation := newAppSettingMutation(c.config, OpUpdate)
	return &AppSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppSettingClient) UpdateOne(_m *AppSetting) *AppSettingUpdateOne {
	mutation := newAppSettingMutation(c.config, OpUpdateOne, withAppSetting(_m))
	return &AppSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppSettingClient) UpdateOneID(id int) *AppSettingUpdateOne {
	mutation := newAppSettingMutation(c.config, OpUpdateOne, withAppSettingID(id))
	return &AppSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppSetting.
func (c *AppSettingClient) Delete() *AppSettingDelete {
	mutation := newAppSettingMutation(c.config, OpDelete)
	return &AppSettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppSettingClient) DeleteOne(_m *AppSetting) *AppSettingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AppSettingClient) DeleteOneID(id int) *AppSettingDeleteOne {
	builder := c.Delete().Where(appsetting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppSettingDeleteOne{builder}
}

// Query returns a query builder for AppSetting.
func (c *AppSettingClient) Query() *AppSettingQuery {
	return &AppSettingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAppSetting},
		inters: c.Interceptors(),
	}
}

// Get returns a AppSetting entity by its id.
func (c *AppSettingClient) Get(ctx context.Context, id int) (*AppSetting, error) {
	return c.Query().Where(appsetting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppSettingClient) GetX(ctx context.Context, id int) *AppSetting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AppSettingClient) Hooks() []Hook {
	return c.hooks.AppSetting
}

// Interceptors returns the client interceptors.
func (c *AppSettingClient) Interceptors() []Interceptor {
	return c.inters.AppSetting
}

func (c *AppSettingClient) mutate(ctx context.Context, m *AppSettingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AppSettingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AppSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AppSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AppSettingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AppSetting mutation op: %q", m.Op())
	}
}

// CalendarEventClient is a client for the CalendarEvent schema.
type CalendarEventClient struct {
	config
}

// NewCalendarEventClient returns a client for the CalendarEvent from the given config.
func NewCalendarEventClient(c config) *CalendarEventClient {
	return &CalendarEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `calendarevent.Hooks(f(g(h())))`.
func (c *CalendarEventClient) Use(hooks ...Hook) {
	c.hooks.CalendarEvent = append(c.hooks.CalendarEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `calendarevent.Intercept(f(g(h())))`.
func (c *CalendarEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.CalendarEvent = append(c.inters.CalendarEvent, interceptors...)
}

// Create returns a builder for creating a CalendarEvent entity.
func (c *CalendarEventClient) Create() *CalendarEventCreate {
	mutation := newCalendarEventMutation(c.config, OpCreate)
	return &CalendarEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CalendarEvent entities.
func (c *CalendarEventClient) CreateBulk(builders ...*CalendarEventCreate) *CalendarEventCreateBulk {
	return &CalendarEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CalendarEventClient) MapCreateBulk(slice any, setFunc func(*CalendarEventCreate, int)) *CalendarEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CalendarEventCreateBulk{err: fmt.Errorf("calling to CalendarEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CalendarEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CalendarEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CalendarEvent.
func (c *CalendarEventClient) Update() *CalendarEventUpdate {
	mutation := newCalendarEventMutation(c.config, OpUpdate)
	return &CalendarEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CalendarEventClient) UpdateOne(_m *CalendarEvent) *CalendarEventUpdateOne {
	mutation := newCalendarEventMutation(c.config, OpUpdateOne, withCalendarEvent(_m))
	return &CalendarEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CalendarEventClient) UpdateOneID(id int) *CalendarEventUpdateOne {
	mutation := newCalendarEventMutation(c.config, OpUpdateOne, withCalendarEventID(id))
	return &CalendarEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CalendarEvent.
func (c *CalendarEventClient) Delete() *CalendarEventDelete {
	mutation := newCalendarEventMutation(c.config, OpDelete)
	return &CalendarEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CalendarEventClient) DeleteOne(_m *CalendarEvent) *CalendarEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CalendarEventClient) DeleteOneID(id int) *CalendarEventDeleteOne {
	builder := c.Delete().Where(calendarevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CalendarEventDeleteOne{builder}
}

// Query returns a query builder for CalendarEvent.
func (c *CalendarEventClient) Query() *CalendarEventQuery {
	return &CalendarEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCalendarEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a CalendarEvent entity by its id.
func (c *CalendarEventClient) Get(ctx context.Context, id int) (*CalendarEvent, error) {
	return c.Query().Where(calendarevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CalendarEventClient) GetX(ctx context.Context, id int) *CalendarEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProposal queries the proposal edge of a CalendarEvent.
func (c *CalendarEventClient) QueryProposal(_m *CalendarEvent) *EventProposalQuery {
	query := (&EventProposalClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(calendarevent.Table, calendarevent.FieldID, id),
			sqlgraph.To(eventproposal.Table, eventproposal.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, calendarevent.ProposalTable, calendarevent.ProposalColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CalendarEventClient) Hooks() []Hook {
	return c.hooks.CalendarEvent
}

// Interceptors returns the client interceptors.
func (c *CalendarEventClient) Interceptors() []Interceptor {
	return c.inters.CalendarEvent
}

func (c *CalendarEventClient) mutate(ctx context.Context, m *CalendarEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CalendarEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CalendarEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CalendarEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CalendarEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CalendarEvent mutation op: %q", m.Op())
	}
}

// ConversationClient is a client for the Conversation schema.
type ConversationClient struct {
	config
}

// NewConversationClient returns a client for the Conversation from the given config.
func NewConversationClient(c config) *ConversationClient {
	return &ConversationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `conversation.Hooks(f(g(h())))`.
func (c *ConversationClient) Use(hooks ...Hook) {
	c.hooks.Conversation = append(c.hooks.Conversation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `conversation.Intercept(f(g(h())))`.
func (c *ConversationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Conversation = append(c.inters.Conversation, interceptors...)
}

// Create returns a builder for creating a Conversation entity.
func (c *ConversationClient) Create() *ConversationCreate {
	mutation := newConversationMutation(c.config, OpCreate)
	return &ConversationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Conversation entities.
func (c *ConversationClient) CreateBulk(builders ...*ConversationCreate) *ConversationCreateBulk {
	return &ConversationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConversationClient) MapCreateBulk(slice any, setFunc func(*ConversationCreate, int)) *ConversationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConversationCreateBulk{err: fmt.Errorf("calling to ConversationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConversationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConversationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Conversation.
func (c *ConversationClient) Update() *ConversationUpdate {
	mutation := newConversationMutation(c.config, OpUpdate)
	return &ConversationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConversationClient) UpdateOne(_m *Conversation) *ConversationUpdateOne {
	mutation := newConversationMutation(c.config, OpUpdateOne, withConversation(_m))
	return &ConversationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ConversationClient) UpdateOneID(id int) *ConversationUpdateOne {
	mutation := newConversationMutation(c.config, OpUpdateOne, withConversationID(id))
	return &ConversationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Conversation.
func (c *ConversationClient) Delete() *ConversationDelete {
	mutation := newConversationMutation(c.config, OpDelete)
	return &ConversationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConversationClient) DeleteOne(_m *Conversation) *ConversationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConversationClient) DeleteOneID(id int) *ConversationDeleteOne {
	builder := c.Delete().Where(conversation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConversationDeleteOne{builder}
}

// Query returns a query builder for Conversation.
func (c *ConversationClient) Query() *ConversationQuery {
	return &ConversationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeConversation},
		inters: c.Interceptors(),
	}
}

// Get returns a Conversation entity by its id.
func (c *ConversationClient) Get(ctx context.Context, id int) (*Conversation, error) {
	return c.Query().Where(conversation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConversationClient) GetX(ctx context.Context, id int) *Conversation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMessages queries the messages edge of a Conversation.
func (c *ConversationClient) QueryMessages(_m *Conversation) *MessageQuery {
	query := (&MessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(conversation.Table, conversation.FieldID, id),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, conversation.MessagesTable, conversation.MessagesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProposals queries the proposals edge of a Conversation.
func (c *ConversationClient) QueryProposals(_m *Conversation) *EventProposalQuery {
	query := (&EventProposalClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(conversation.Table, conversation.FieldID, id),
			sqlgraph.To(eventproposal.Table, eventproposal.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, conversation.ProposalsTable, conversation.ProposalsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ConversationClient) Hooks() []Hook {
	return c.hooks.Conversation
}

// Interceptors returns the client interceptors.
func (c *ConversationClient) Interceptors() []Interceptor {
	return c.inters.Conversation
}

func (c *ConversationClient) mutate(ctx context.Context, m *ConversationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConversationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConversationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConversationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConversationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Conversation mutation op: %q", m.Op())
	}
}

// EventProposalClient is a client for the EventProposal schema.
type EventProposalClient struct {
	config
}

// NewEventProposalClient returns a client for the EventProposal from the given config.
func NewEventProposalClient(c config) *EventProposalClient {
	return &EventProposalClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `eventproposal.Hooks(f(g(h())))`.
func (c *EventProposalClient) Use(hooks ...Hook) {
	c.hooks.EventProposal = append(c.hooks.EventProposal, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `eventproposal.Intercept(f(g(h())))`.
func (c *EventProposalClient) Intercept(interceptors ...Interceptor) {
	c.inters.EventProposal = append(c.inters.EventProposal, interceptors...)
}

// Create returns a builder for creating a EventProposal entity.
func (c *EventProposalClient) Create() *EventProposalCreate {
	mutation := newEventProposalMutation(c.config, OpCreate)
	return &EventProposalCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EventProposal entities.
func (c *EventProposalClient) CreateBulk(builders ...*EventProposalCreate) *EventProposalCreateBulk {
	return &EventProposalCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EventProposalClient) MapCreateBulk(slice any, setFunc func(*EventProposalCreate, int)) *EventProposalCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EventProposalCreateBulk{err: fmt.Errorf("calling to EventProposalClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EventProposalCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EventProposalCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EventProposal.
func (c *EventProposalClient) Update() *EventProposalUpdate {
	mutation := newEventProposalMutation(c.config, OpUpdate)
	return &EventProposalUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EventProposalClient) UpdateOne(_m *EventProposal) *EventProposalUpdateOne {
	mutation := newEventProposalMutation(c.config, OpUpdateOne, withEventProposal(_m))
	return &EventProposalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EventProposalClient) UpdateOneID(id int) *EventProposalUpdateOne {
	mutation := newEventProposalMutation(c.config, OpUpdateOne, withEventProposalID(id))
	return &EventProposalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EventProposal.
func (c *EventProposalClient) Delete() *EventProposalDelete {
	mutation := newEventProposalMutation(c.config, OpDelete)
	return &EventProposalDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EventProposalClient) DeleteOne(_m *EventProposal) *EventProposalDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EventProposalClient) DeleteOneID(id int) *EventProposalDeleteOne {
	builder := c.Delete().Where(eventproposal.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EventProposalDeleteOne{builder}
}

// Query returns a query builder for EventProposal.
func (c *EventProposalClient) Query() *EventProposalQuery {
	return &EventProposalQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEventProposal},
		inters: c.Interceptors(),
	}
}

// Get returns a EventProposal entity by its id.
func (c *EventProposalClient) Get(ctx context.Context, id int) (*EventProposal, error) {
	return c.Query().Where(eventproposal.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EventProposalClient) GetX(ctx context.Context, id int) *EventProposal {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryConversation queries the conversation edge of a EventProposal.
func (c *EventProposalClient) QueryConversation(_m *EventProposal) *ConversationQuery {
	query := (&ConversationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(eventproposal.Table, eventproposal.FieldID, id),
			sqlgraph.To(conversation.Table, conversation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, eventproposal.ConversationTable, eventproposal.ConversationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMessage queries the message edge of a EventProposal.
func (c *EventProposalClient) QueryMessage(_m *EventProposal) *MessageQuery {
	query := (&MessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(eventproposal.Table, eventproposal.FieldID, id),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, eventproposal.MessageTable, eventproposal.MessageColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCalendarEvent queries the calendar_event edge of a EventProposal.
func (c *EventProposalClient) QueryCalendarEvent(_m *EventProposal) *CalendarEventQuery {
	query := (&CalendarEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(eventproposal.Table, eventproposal.FieldID, id),
			sqlgraph.To(calendarevent.Table, calendarevent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, eventproposal.CalendarEventTable, eventproposal.CalendarEventColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EventProposalClient) Hooks() []Hook {
	return c.hooks.EventProposal
}

// Interceptors returns the client interceptors.
func (c *EventProposalClient) Interceptors() []Interceptor {
	return c.inters.EventProposal
}

func (c *EventProposalClient) mutate(ctx context.Context, m *EventProposalMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EventProposalCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EventProposalUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EventProposalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EventProposalDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EventProposal mutation op: %q", m.Op())
	}
}

// MessageClient is a client for the Message schema.
type MessageClient struct {
	config
}

// NewMessageClient returns a client for the Message from the given config.
func NewMessageClient(c config) *MessageClient {
	return &MessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `message.Hooks(f(g(h())))`.
func (c *MessageClient) Use(hooks ...Hook) {
	c.hooks.Message = append(c.hooks.Message, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `message.Intercept(f(g(h())))`.
func (c *MessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.Message = append(c.inters.Message, interceptors...)
}

// Create returns a builder for creating a Message entity.
func (c *MessageClient) Create() *MessageCreate {
	mutation := newMessageMutation(c.config, OpCreate)
	return &MessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Message entities.
func (c *MessageClient) CreateBulk(builders ...*MessageCreate) *MessageCreateBulk {
	return &MessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MessageClient) MapCreateBulk(slice any, setFunc func(*MessageCreate, int)) *MessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MessageCreateBulk{err: fmt.Errorf("calling to MessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Message.
func (c *MessageClient) Update() *MessageUpdate {
	mutation := newMessageMutation(c.config, OpUpdate)
	return &MessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MessageClient) UpdateOne(_m *Message) *MessageUpdateOne {
	mutation := newMessageMutation(c.config, OpUpdateOne, withMessage(_m))
	return &MessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MessageClient) UpdateOneID(id int) *MessageUpdateOne {
	mutation := newMessageMutation(c.config, OpUpdateOne, withMessageID(id))
	return &MessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Message.
func (c *MessageClient) Delete() *MessageDelete {
	mutation := newMessageMutation(c.config, OpDelete)
	return &MessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MessageClient) DeleteOne(_m *Message) *MessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MessageClient) DeleteOneID(id int) *MessageDeleteOne {
	builder := c.Delete().Where(message.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MessageDeleteOne{builder}
}

// Query returns a query builder for Message.
func (c *MessageClient) Query() *MessageQuery {
	return &MessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a Message entity by its id.
func (c *MessageClient) Get(ctx context.Context, id int) (*Message, error) {
	return c.Query().Where(message.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MessageClient) GetX(ctx context.Context, id int) *Message {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryConversation queries the conversation edge of a Message.
func (c *MessageClient) QueryConversation(_m *Message) *ConversationQuery {
	query := (&ConversationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(message.Table, message.FieldID, id),
			sqlgraph.To(conversation.Table, conversation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, message.ConversationTable, message.ConversationColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProposals queries the proposals edge of a Message.
func (c *MessageClient) QueryProposals(_m *Message) *EventProposalQuery {
	query := (&EventProposalClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(message.Table, message.FieldID, id),
			sqlgraph.To(eventproposal.Table, eventproposal.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, message.ProposalsTable, message.ProposalsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MessageClient) Hooks() []Hook {
	return c.hooks.Message
}

// Interceptors returns the client interceptors.
func (c *MessageClient) Interceptors() []Interceptor {
	return c.inters.Message
}

func (c *MessageClient) mutate(ctx context.Context, m *MessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Message mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AppSetting, CalendarEvent, Conversation, EventProposal, Message []ent.Hook
	}
	inters struct {
		AppSetting, CalendarEvent, Conversation, EventProposal,
		Message []ent.Interceptor
	}
)
