// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ITK13201/CalendarRabbit/backend/ent/calendarevent"
	"github.com/ITK13201/CalendarRabbit/backend/ent/conversation"
	"github.com/ITK13201/CalendarRabbit/backend/ent/eventproposal"
	"github.com/ITK13201/CalendarRabbit/backend/ent/message"
	"github.com/ITK13201/CalendarRabbit/backend/ent/predicate"
)

// EventProposalUpdate is the builder for updating EventProposal entities.
type EventProposalUpdate struct {
	config
	hooks    []Hook
	mutation *EventProposalMutation
}

// Where appends a list predicates to the EventProposalUpdate builder.
func (_u *EventProposalUpdate) Where(ps ...predicate.EventProposal) *EventProposalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *EventProposalUpdate) SetTitle(v string) *EventProposalUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EventProposalUpdate) SetNillableTitle(v *string) *EventProposalUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *EventProposalUpdate) SetStartsAt(v time.Time) *EventProposalUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *EventProposalUpdate) SetNillableStartsAt(v *time.Time) *EventProposalUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *EventProposalUpdate) SetEndsAt(v time.Time) *EventProposalUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *EventProposalUpdate) SetNillableEndsAt(v *time.Time) *EventProposalUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// SetAllDay sets the "all_day" field.
func (_u *EventProposalUpdate) SetAllDay(v bool) *EventProposalUpdate {
	_u.mutation.SetAllDay(v)
	return _u
}

// SetNillableAllDay sets the "all_day" field if the given value is not nil.
func (_u *EventProposalUpdate) SetNillableAllDay(v *bool) *EventProposalUpdate {
	if v != nil {
		_u.SetAllDay(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *EventProposalUpdate) SetLocation(v string) *EventProposalUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *EventProposalUpdate) SetNillableLocation(v *string) *EventProposalUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *EventProposalUpdate) SetDescription(v string) *EventProposalUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EventProposalUpdate) SetNillableDescription(v *string) *EventProposalUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *EventProposalUpdate) SetSourceURL(v string) *EventProposalUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *EventProposalUpdate) SetNillableSourceURL(v *string) *EventProposalUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EventProposalUpdate) SetStatus(v eventproposal.Status) *EventProposalUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventProposalUpdate) SetNillableStatus(v *eventproposal.Status) *EventProposalUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventProposalUpdate) SetUpdatedAt(v time.Time) *EventProposalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConversationID sets the "conversation" edge to the Conversation entity by ID.
func (_u *EventProposalUpdate) SetConversationID(id int) *EventProposalUpdate {
	_u.mutation.SetConversationID(id)
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *EventProposalUpdate) SetConversation(v *Conversation) *EventProposalUpdate {
	return _u.SetConversationID(v.ID)
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (_u *EventProposalUpdate) SetMessageID(id int) *EventProposalUpdate {
	_u.mutation.SetMessageID(id)
	return _u
}

// SetNillableMessageID sets the "message" edge to the Message entity by ID if the given value is not nil.
func (_u *EventProposalUpdate) SetNillableMessageID(id *int) *EventProposalUpdate {
	if id != nil {
		_u = _u.SetMessageID(*id)
	}
	return _u
}

// SetMessage sets the "message" edge to the Message entity.
func (_u *EventProposalUpdate) SetMessage(v *Message) *EventProposalUpdate {
	return _u.SetMessageID(v.ID)
}

// SetCalendarEventID sets the "calendar_event" edge to the CalendarEvent entity by ID.
func (_u *EventProposalUpdate) SetCalendarEventID(id int) *EventProposalUpdate {
	_u.mutation.SetCalendarEventID(id)
	return _u
}

// SetNillableCalendarEventID sets the "calendar_event" edge to the CalendarEvent entity by ID if the given value is not nil.
func (_u *EventProposalUpdate) SetNillableCalendarEventID(id *int) *EventProposalUpdate {
	if id != nil {
		_u = _u.SetCalendarEventID(*id)
	}
	return _u
}

// SetCalendarEvent sets the "calendar_event" edge to the CalendarEvent entity.
func (_u *EventProposalUpdate) SetCalendarEvent(v *CalendarEvent) *EventProposalUpdate {
	return _u.SetCalendarEventID(v.ID)
}

// Mutation returns the EventProposalMutation object of the builder.
func (_u *EventProposalUpdate) Mutation() *EventProposalMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *EventProposalUpdate) ClearConversation() *EventProposalUpdate {
	_u.mutation.ClearConversation()
	return _u
}

// ClearMessage clears the "message" edge to the Message entity.
func (_u *EventProposalUpdate) ClearMessage() *EventProposalUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// ClearCalendarEvent clears the "calendar_event" edge to the CalendarEvent entity.
func (_u *EventProposalUpdate) ClearCalendarEvent() *EventProposalUpdate {
	_u.mutation.ClearCalendarEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventProposalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventProposalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventProposalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventProposalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventProposalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := eventproposal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventProposalUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := eventproposal.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "EventProposal.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := eventproposal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EventProposal.status": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EventProposal.conversation"`)
	}
	return nil
}

func (_u *EventProposalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventproposal.Table, eventproposal.Columns, sqlgraph.NewFieldSpec(eventproposal.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(eventproposal.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(eventproposal.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(eventproposal.FieldEndsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AllDay(); ok {
		_spec.SetField(eventproposal.FieldAllDay, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(eventproposal.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(eventproposal.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(eventproposal.FieldSourceURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(eventproposal.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(eventproposal.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventproposal.ConversationTable,
			Columns: []string{eventproposal.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventproposal.ConversationTable,
			Columns: []string{eventproposal.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventproposal.MessageTable,
			Columns: []string{eventproposal.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventproposal.MessageTable,
			Columns: []string{eventproposal.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CalendarEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   eventproposal.CalendarEventTable,
			Columns: []string{eventproposal.CalendarEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CalendarEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   eventproposal.CalendarEventTable,
			Columns: []string{eventproposal.CalendarEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventproposal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventProposalUpdateOne is the builder for updating a single EventProposal entity.
type EventProposalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventProposalMutation
}

// SetTitle sets the "title" field.
func (_u *EventProposalUpdateOne) SetTitle(v string) *EventProposalUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *EventProposalUpdateOne) SetNillableTitle(v *string) *EventProposalUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *EventProposalUpdateOne) SetStartsAt(v time.Time) *EventProposalUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *EventProposalUpdateOne) SetNillableStartsAt(v *time.Time) *EventProposalUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *EventProposalUpdateOne) SetEndsAt(v time.Time) *EventProposalUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *EventProposalUpdateOne) SetNillableEndsAt(v *time.Time) *EventProposalUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// SetAllDay sets the "all_day" field.
func (_u *EventProposalUpdateOne) SetAllDay(v bool) *EventProposalUpdateOne {
	_u.mutation.SetAllDay(v)
	return _u
}

// SetNillableAllDay sets the "all_day" field if the given value is not nil.
func (_u *EventProposalUpdateOne) SetNillableAllDay(v *bool) *EventProposalUpdateOne {
	if v != nil {
		_u.SetAllDay(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *EventProposalUpdateOne) SetLocation(v string) *EventProposalUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *EventProposalUpdateOne) SetNillableLocation(v *string) *EventProposalUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *EventProposalUpdateOne) SetDescription(v string) *EventProposalUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EventProposalUpdateOne) SetNillableDescription(v *string) *EventProposalUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *EventProposalUpdateOne) SetSourceURL(v string) *EventProposalUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *EventProposalUpdateOne) SetNillableSourceURL(v *string) *EventProposalUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EventProposalUpdateOne) SetStatus(v eventproposal.Status) *EventProposalUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EventProposalUpdateOne) SetNillableStatus(v *eventproposal.Status) *EventProposalUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventProposalUpdateOne) SetUpdatedAt(v time.Time) *EventProposalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConversationID sets the "conversation" edge to the Conversation entity by ID.
func (_u *EventProposalUpdateOne) SetConversationID(id int) *EventProposalUpdateOne {
	_u.mutation.SetConversationID(id)
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *EventProposalUpdateOne) SetConversation(v *Conversation) *EventProposalUpdateOne {
	return _u.SetConversationID(v.ID)
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (_u *EventProposalUpdateOne) SetMessageID(id int) *EventProposalUpdateOne {
	_u.mutation.SetMessageID(id)
	return _u
}

// SetNillableMessageID sets the "message" edge to the Message entity by ID if the given value is not nil.
func (_u *EventProposalUpdateOne) SetNillableMessageID(id *int) *EventProposalUpdateOne {
	if id != nil {
		_u = _u.SetMessageID(*id)
	}
	return _u
}

// SetMessage sets the "message" edge to the Message entity.
func (_u *EventProposalUpdateOne) SetMessage(v *Message) *EventProposalUpdateOne {
	return _u.SetMessageID(v.ID)
}

// SetCalendarEventID sets the "calendar_event" edge to the CalendarEvent entity by ID.
func (_u *EventProposalUpdateOne) SetCalendarEventID(id int) *EventProposalUpdateOne {
	_u.mutation.SetCalendarEventID(id)
	return _u
}

// SetNillableCalendarEventID sets the "calendar_event" edge to the CalendarEvent entity by ID if the given value is not nil.
func (_u *EventProposalUpdateOne) SetNillableCalendarEventID(id *int) *EventProposalUpdateOne {
	if id != nil {
		_u = _u.SetCalendarEventID(*id)
	}
	return _u
}

// SetCalendarEvent sets the "calendar_event" edge to the CalendarEvent entity.
func (_u *EventProposalUpdateOne) SetCalendarEvent(v *CalendarEvent) *EventProposalUpdateOne {
	return _u.SetCalendarEventID(v.ID)
}

// Mutation returns the EventProposalMutation object of the builder.
func (_u *EventProposalUpdateOne) Mutation() *EventProposalMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *EventProposalUpdateOne) ClearConversation() *EventProposalUpdateOne {
	_u.mutation.ClearConversation()
	return _u
}

// ClearMessage clears the "message" edge to the Message entity.
func (_u *EventProposalUpdateOne) ClearMessage() *EventProposalUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// ClearCalendarEvent clears the "calendar_event" edge to the CalendarEvent entity.
func (_u *EventProposalUpdateOne) ClearCalendarEvent() *EventProposalUpdateOne {
	_u.mutation.ClearCalendarEvent()
	return _u
}

// Where appends a list predicates to the EventProposalUpdate builder.
func (_u *EventProposalUpdateOne) Where(ps ...predicate.EventProposal) *EventProposalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventProposalUpdateOne) Select(field string, fields ...string) *EventProposalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EventProposal entity.
func (_u *EventProposalUpdateOne) Save(ctx context.Context) (*EventProposal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventProposalUpdateOne) SaveX(ctx context.Context) *EventProposal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventProposalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventProposalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventProposalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := eventproposal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventProposalUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := eventproposal.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "EventProposal.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := eventproposal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EventProposal.status": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EventProposal.conversation"`)
	}
	return nil
}

func (_u *EventProposalUpdateOne) sqlSave(ctx context.Context) (_node *EventProposal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventproposal.Table, eventproposal.Columns, sqlgraph.NewFieldSpec(eventproposal.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EventProposal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventproposal.FieldID)
		for _, f := range fields {
			if !eventproposal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != eventproposal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(eventproposal.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(eventproposal.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(eventproposal.FieldEndsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AllDay(); ok {
		_spec.SetField(eventproposal.FieldAllDay, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(eventproposal.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(eventproposal.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(eventproposal.FieldSourceURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(eventproposal.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(eventproposal.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventproposal.ConversationTable,
			Columns: []string{eventproposal.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventproposal.ConversationTable,
			Columns: []string{eventproposal.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventproposal.MessageTable,
			Columns: []string{eventproposal.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventproposal.MessageTable,
			Columns: []string{eventproposal.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CalendarEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   eventproposal.CalendarEventTable,
			Columns: []string{eventproposal.CalendarEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CalendarEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   eventproposal.CalendarEventTable,
			Columns: []string{eventproposal.CalendarEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EventProposal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventproposal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
