// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ITK13201/CalendarRabbit/backend/ent/calendarevent"
	"github.com/ITK13201/CalendarRabbit/backend/ent/conversation"
	"github.com/ITK13201/CalendarRabbit/backend/ent/eventproposal"
	"github.com/ITK13201/CalendarRabbit/backend/ent/message"
)

// EventProposalCreate is the builder for creating a EventProposal entity.
type EventProposalCreate struct {
	config
	mutation *EventProposalMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *EventProposalCreate) SetTitle(v string) *EventProposalCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *EventProposalCreate) SetStartsAt(v time.Time) *EventProposalCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *EventProposalCreate) SetEndsAt(v time.Time) *EventProposalCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetAllDay sets the "all_day" field.
func (_c *EventProposalCreate) SetAllDay(v bool) *EventProposalCreate {
	_c.mutation.SetAllDay(v)
	return _c
}

// SetNillableAllDay sets the "all_day" field if the given value is not nil.
func (_c *EventProposalCreate) SetNillableAllDay(v *bool) *EventProposalCreate {
	if v != nil {
		_c.SetAllDay(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *EventProposalCreate) SetLocation(v string) *EventProposalCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *EventProposalCreate) SetNillableLocation(v *string) *EventProposalCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *EventProposalCreate) SetDescription(v string) *EventProposalCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *EventProposalCreate) SetNillableDescription(v *string) *EventProposalCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *EventProposalCreate) SetSourceURL(v string) *EventProposalCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_c *EventProposalCreate) SetNillableSourceURL(v *string) *EventProposalCreate {
	if v != nil {
		_c.SetSourceURL(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EventProposalCreate) SetStatus(v eventproposal.Status) *EventProposalCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EventProposalCreate) SetNillableStatus(v *eventproposal.Status) *EventProposalCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventProposalCreate) SetCreatedAt(v time.Time) *EventProposalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventProposalCreate) SetNillableCreatedAt(v *time.Time) *EventProposalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventProposalCreate) SetUpdatedAt(v time.Time) *EventProposalCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventProposalCreate) SetNillableUpdatedAt(v *time.Time) *EventProposalCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetConversationID sets the "conversation" edge to the Conversation entity by ID.
func (_c *EventProposalCreate) SetConversationID(id int) *EventProposalCreate {
	_c.mutation.SetConversationID(id)
	return _c
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_c *EventProposalCreate) SetConversation(v *Conversation) *EventProposalCreate {
	return _c.SetConversationID(v.ID)
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (_c *EventProposalCreate) SetMessageID(id int) *EventProposalCreate {
	_c.mutation.SetMessageID(id)
	return _c
}

// SetNillableMessageID sets the "message" edge to the Message entity by ID if the given value is not nil.
func (_c *EventProposalCreate) SetNillableMessageID(id *int) *EventProposalCreate {
	if id != nil {
		_c = _c.SetMessageID(*id)
	}
	return _c
}

// SetMessage sets the "message" edge to the Message entity.
func (_c *EventProposalCreate) SetMessage(v *Message) *EventProposalCreate {
	return _c.SetMessageID(v.ID)
}

// SetCalendarEventID sets the "calendar_event" edge to the CalendarEvent entity by ID.
func (_c *EventProposalCreate) SetCalendarEventID(id int) *EventProposalCreate {
	_c.mutation.SetCalendarEventID(id)
	return _c
}

// SetNillableCalendarEventID sets the "calendar_event" edge to the CalendarEvent entity by ID if the given value is not nil.
func (_c *EventProposalCreate) SetNillableCalendarEventID(id *int) *EventProposalCreate {
	if id != nil {
		_c = _c.SetCalendarEventID(*id)
	}
	return _c
}

// SetCalendarEvent sets the "calendar_event" edge to the CalendarEvent entity.
func (_c *EventProposalCreate) SetCalendarEvent(v *CalendarEvent) *EventProposalCreate {
	return _c.SetCalendarEventID(v.ID)
}

// Mutation returns the EventProposalMutation object of the builder.
func (_c *EventProposalCreate) Mutation() *EventProposalMutation {
	return _c.mutation
}

// Save creates the EventProposal in the database.
func (_c *EventProposalCreate) Save(ctx context.Context) (*EventProposal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventProposalCreate) SaveX(ctx context.Context) *EventProposal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventProposalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventProposalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventProposalCreate) defaults() {
	if _, ok := _c.mutation.AllDay(); !ok {
		v := eventproposal.DefaultAllDay
		_c.mutation.SetAllDay(v)
	}
	if _, ok := _c.mutation.Location(); !ok {
		v := eventproposal.DefaultLocation
		_c.mutation.SetLocation(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := eventproposal.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.SourceURL(); !ok {
		v := eventproposal.DefaultSourceURL
		_c.mutation.SetSourceURL(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := eventproposal.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := eventproposal.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := eventproposal.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventProposalCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "EventProposal.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := eventproposal.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "EventProposal.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "EventProposal.starts_at"`)}
	}
	if _, ok := _c.mutation.EndsAt(); !ok {
		return &ValidationError{Name: "ends_at", err: errors.New(`ent: missing required field "EventProposal.ends_at"`)}
	}
	if _, ok := _c.mutation.AllDay(); !ok {
		return &ValidationError{Name: "all_day", err: errors.New(`ent: missing required field "EventProposal.all_day"`)}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "EventProposal.location"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "EventProposal.description"`)}
	}
	if _, ok := _c.mutation.SourceURL(); !ok {
		return &ValidationError{Name: "source_url", err: errors.New(`ent: missing required field "EventProposal.source_url"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EventProposal.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := eventproposal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EventProposal.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EventProposal.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EventProposal.updated_at"`)}
	}
	if len(_c.mutation.ConversationIDs()) == 0 {
		return &ValidationError{Name: "conversation", err: errors.New(`ent: missing required edge "EventProposal.conversation"`)}
	}
	return nil
}

func (_c *EventProposalCreate) sqlSave(ctx context.Context) (*EventProposal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventProposalCreate) createSpec() (*EventProposal, *sqlgraph.CreateSpec) {
	var (
		_node = &EventProposal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(eventproposal.Table, sqlgraph.NewFieldSpec(eventproposal.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(eventproposal.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(eventproposal.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(eventproposal.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = value
	}
	if value, ok := _c.mutation.AllDay(); ok {
		_spec.SetField(eventproposal.FieldAllDay, field.TypeBool, value)
		_node.AllDay = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(eventproposal.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(eventproposal.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(eventproposal.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(eventproposal.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(eventproposal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(eventproposal.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventproposal.ConversationTable,
			Columns: []string{eventproposal.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.conversation_proposals = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventproposal.MessageTable,
			Columns: []string{eventproposal.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.message_proposals = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CalendarEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   eventproposal.CalendarEventTable,
			Columns: []string{eventproposal.CalendarEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.event_proposal_calendar_event = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventProposalCreateBulk is the builder for creating many EventProposal entities in bulk.
type EventProposalCreateBulk struct {
	config
	err      error
	builders []*EventProposalCreate
}

// Save creates the EventProposal entities in the database.
func (_c *EventProposalCreateBulk) Save(ctx context.Context) ([]*EventProposal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EventProposal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventProposalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventProposalCreateBulk) SaveX(ctx context.Context) []*EventProposal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventProposalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventProposalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
