// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ITK13201/CalendarRabbit/backend/ent/calendarevent"
	"github.com/ITK13201/CalendarRabbit/backend/ent/conversation"
	"github.com/ITK13201/CalendarRabbit/backend/ent/eventproposal"
	"github.com/ITK13201/CalendarRabbit/backend/ent/message"
)

// EventProposal is the model entity for the EventProposal schema.
type EventProposal struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// EndsAt holds the value of the "ends_at" field.
	EndsAt time.Time `json:"ends_at,omitempty"`
	// AllDay holds the value of the "all_day" field.
	AllDay bool `json:"all_day,omitempty"`
	// Location holds the value of the "location" field.
	Location string `json:"location,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// SourceURL holds the value of the "source_url" field.
	SourceURL string `json:"source_url,omitempty"`
	// Status holds the value of the "status" field.
	Status eventproposal.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EventProposalQuery when eager-loading is set.
	Edges                         EventProposalEdges `json:"edges"`
	conversation_proposals        *int
	event_proposal_calendar_event *int
	message_proposals             *int
	selectValues                  sql.SelectValues
}

// EventProposalEdges holds the relations/edges for other nodes in the graph.
type EventProposalEdges struct {
	// Conversation holds the value of the conversation edge.
	Conversation *Conversation `json:"conversation,omitempty"`
	// Message holds the value of the message edge.
	Message *Message `json:"message,omitempty"`
	// CalendarEvent holds the value of the calendar_event edge.
	CalendarEvent *CalendarEvent `json:"calendar_event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ConversationOrErr returns the Conversation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventProposalEdges) ConversationOrErr() (*Conversation, error) {
	if e.Conversation != nil {
		return e.Conversation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: conversation.Label}
	}
	return nil, &NotLoadedError{edge: "conversation"}
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventProposalEdges) MessageOrErr() (*Message, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: message.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// CalendarEventOrErr returns the CalendarEvent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventProposalEdges) CalendarEventOrErr() (*CalendarEvent, error) {
	if e.CalendarEvent != nil {
		return e.CalendarEvent, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: calendarevent.Label}
	}
	return nil, &NotLoadedError{edge: "calendar_event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EventProposal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case eventproposal.FieldAllDay:
			values[i] = new(sql.NullBool)
		case eventproposal.FieldID:
			values[i] = new(sql.NullInt64)
		case eventproposal.FieldTitle, eventproposal.FieldLocation, eventproposal.FieldDescription, eventproposal.FieldSourceURL, eventproposal.FieldStatus:
			values[i] = new(sql.NullString)
		case eventproposal.FieldStartsAt, eventproposal.FieldEndsAt, eventproposal.FieldCreatedAt, eventproposal.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case eventproposal.ForeignKeys[0]: // conversation_proposals
			values[i] = new(sql.NullInt64)
		case eventproposal.ForeignKeys[1]: // event_proposal_calendar_event
			values[i] = new(sql.NullInt64)
		case eventproposal.ForeignKeys[2]: // message_proposals
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EventProposal fields.
func (_m *EventProposal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case eventproposal.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case eventproposal.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case eventproposal.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case eventproposal.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = value.Time
			}
		case eventproposal.FieldAllDay:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field all_day", values[i])
			} else if value.Valid {
				_m.AllDay = value.Bool
			}
		case eventproposal.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				_m.Location = value.String
			}
		case eventproposal.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case eventproposal.FieldSourceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_url", values[i])
			} else if value.Valid {
				_m.SourceURL = value.String
			}
		case eventproposal.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = eventproposal.Status(value.String)
			}
		case eventproposal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case eventproposal.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case eventproposal.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field conversation_proposals", value)
			} else if value.Valid {
				_m.conversation_proposals = new(int)
				*_m.conversation_proposals = int(value.Int64)
			}
		case eventproposal.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field event_proposal_calendar_event", value)
			} else if value.Valid {
				_m.event_proposal_calendar_event = new(int)
				*_m.event_proposal_calendar_event = int(value.Int64)
			}
		case eventproposal.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field message_proposals", value)
			} else if value.Valid {
				_m.message_proposals = new(int)
				*_m.message_proposals = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EventProposal.
// This includes values selected through modifiers, order, etc.
func (_m *EventProposal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConversation queries the "conversation" edge of the EventProposal entity.
func (_m *EventProposal) QueryConversation() *ConversationQuery {
	return NewEventProposalClient(_m.config).QueryConversation(_m)
}

// QueryMessage queries the "message" edge of the EventProposal entity.
func (_m *EventProposal) QueryMessage() *MessageQuery {
	return NewEventProposalClient(_m.config).QueryMessage(_m)
}

// QueryCalendarEvent queries the "calendar_event" edge of the EventProposal entity.
func (_m *EventProposal) QueryCalendarEvent() *CalendarEventQuery {
	return NewEventProposalClient(_m.config).QueryCalendarEvent(_m)
}

// Update returns a builder for updating this EventProposal.
// Note that you need to call EventProposal.Unwrap() before calling this method if this EventProposal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EventProposal) Update() *EventProposalUpdateOne {
	return NewEventProposalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EventProposal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EventProposal) Unwrap() *EventProposal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EventProposal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EventProposal) String() string {
	var builder strings.Builder
	builder.WriteString("EventProposal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ends_at=")
	builder.WriteString(_m.EndsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("all_day=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllDay))
	builder.WriteString(", ")
	builder.WriteString("location=")
	builder.WriteString(_m.Location)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("source_url=")
	builder.WriteString(_m.SourceURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EventProposals is a parsable slice of EventProposal.
type EventProposals []*EventProposal
