// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ITK13201/CalendarRabbit/backend/ent/googleconnection"
)

// GoogleConnectionCreate is the builder for creating a GoogleConnection entity.
type GoogleConnectionCreate struct {
	config
	mutation *GoogleConnectionMutation
	hooks    []Hook
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *GoogleConnectionCreate) SetRefreshToken(v string) *GoogleConnectionCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_c *GoogleConnectionCreate) SetNillableRefreshToken(v *string) *GoogleConnectionCreate {
	if v != nil {
		_c.SetRefreshToken(*v)
	}
	return _c
}

// SetAccessToken sets the "access_token" field.
func (_c *GoogleConnectionCreate) SetAccessToken(v string) *GoogleConnectionCreate {
	_c.mutation.SetAccessToken(v)
	return _c
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_c *GoogleConnectionCreate) SetNillableAccessToken(v *string) *GoogleConnectionCreate {
	if v != nil {
		_c.SetAccessToken(*v)
	}
	return _c
}

// SetTokenExpiry sets the "token_expiry" field.
func (_c *GoogleConnectionCreate) SetTokenExpiry(v time.Time) *GoogleConnectionCreate {
	_c.mutation.SetTokenExpiry(v)
	return _c
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_c *GoogleConnectionCreate) SetNillableTokenExpiry(v *time.Time) *GoogleConnectionCreate {
	if v != nil {
		_c.SetTokenExpiry(*v)
	}
	return _c
}

// SetCalendarID sets the "calendar_id" field.
func (_c *GoogleConnectionCreate) SetCalendarID(v string) *GoogleConnectionCreate {
	_c.mutation.SetCalendarID(v)
	return _c
}

// SetNillableCalendarID sets the "calendar_id" field if the given value is not nil.
func (_c *GoogleConnectionCreate) SetNillableCalendarID(v *string) *GoogleConnectionCreate {
	if v != nil {
		_c.SetCalendarID(*v)
	}
	return _c
}

// SetConnected sets the "connected" field.
func (_c *GoogleConnectionCreate) SetConnected(v bool) *GoogleConnectionCreate {
	_c.mutation.SetConnected(v)
	return _c
}

// SetNillableConnected sets the "connected" field if the given value is not nil.
func (_c *GoogleConnectionCreate) SetNillableConnected(v *bool) *GoogleConnectionCreate {
	if v != nil {
		_c.SetConnected(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GoogleConnectionCreate) SetCreatedAt(v time.Time) *GoogleConnectionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GoogleConnectionCreate) SetNillableCreatedAt(v *time.Time) *GoogleConnectionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GoogleConnectionCreate) SetUpdatedAt(v time.Time) *GoogleConnectionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GoogleConnectionCreate) SetNillableUpdatedAt(v *time.Time) *GoogleConnectionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the GoogleConnectionMutation object of the builder.
func (_c *GoogleConnectionCreate) Mutation() *GoogleConnectionMutation {
	return _c.mutation
}

// Save creates the GoogleConnection in the database.
func (_c *GoogleConnectionCreate) Save(ctx context.Context) (*GoogleConnection, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GoogleConnectionCreate) SaveX(ctx context.Context) *GoogleConnection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoogleConnectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoogleConnectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GoogleConnectionCreate) defaults() {
	if _, ok := _c.mutation.RefreshToken(); !ok {
		v := googleconnection.DefaultRefreshToken
		_c.mutation.SetRefreshToken(v)
	}
	if _, ok := _c.mutation.AccessToken(); !ok {
		v := googleconnection.DefaultAccessToken
		_c.mutation.SetAccessToken(v)
	}
	if _, ok := _c.mutation.CalendarID(); !ok {
		v := googleconnection.DefaultCalendarID
		_c.mutation.SetCalendarID(v)
	}
	if _, ok := _c.mutation.Connected(); !ok {
		v := googleconnection.DefaultConnected
		_c.mutation.SetConnected(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := googleconnection.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := googleconnection.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GoogleConnectionCreate) check() error {
	if _, ok := _c.mutation.RefreshToken(); !ok {
		return &ValidationError{Name: "refresh_token", err: errors.New(`ent: missing required field "GoogleConnection.refresh_token"`)}
	}
	if _, ok := _c.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`ent: missing required field "GoogleConnection.access_token"`)}
	}
	if _, ok := _c.mutation.CalendarID(); !ok {
		return &ValidationError{Name: "calendar_id", err: errors.New(`ent: missing required field "GoogleConnection.calendar_id"`)}
	}
	if _, ok := _c.mutation.Connected(); !ok {
		return &ValidationError{Name: "connected", err: errors.New(`ent: missing required field "GoogleConnection.connected"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GoogleConnection.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GoogleConnection.updated_at"`)}
	}
	return nil
}

func (_c *GoogleConnectionCreate) sqlSave(ctx context.Context) (*GoogleConnection, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GoogleConnectionCreate) createSpec() (*GoogleConnection, *sqlgraph.CreateSpec) {
	var (
		_node = &GoogleConnection{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(googleconnection.Table, sqlgraph.NewFieldSpec(googleconnection.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(googleconnection.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := _c.mutation.AccessToken(); ok {
		_spec.SetField(googleconnection.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := _c.mutation.TokenExpiry(); ok {
		_spec.SetField(googleconnection.FieldTokenExpiry, field.TypeTime, value)
		_node.TokenExpiry = value
	}
	if value, ok := _c.mutation.CalendarID(); ok {
		_spec.SetField(googleconnection.FieldCalendarID, field.TypeString, value)
		_node.CalendarID = value
	}
	if value, ok := _c.mutation.Connected(); ok {
		_spec.SetField(googleconnection.FieldConnected, field.TypeBool, value)
		_node.Connected = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(googleconnection.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(googleconnection.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GoogleConnectionCreateBulk is the builder for creating many GoogleConnection entities in bulk.
type GoogleConnectionCreateBulk struct {
	config
	err      error
	builders []*GoogleConnectionCreate
}

// Save creates the GoogleConnection entities in the database.
func (_c *GoogleConnectionCreateBulk) Save(ctx context.Context) ([]*GoogleConnection, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GoogleConnection, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoogleConnectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GoogleConnectionCreateBulk) SaveX(ctx context.Context) []*GoogleConnection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoogleConnectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoogleConnectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
