// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ITK13201/CalendarRabbit/backend/ent/googleconnection"
	"github.com/ITK13201/CalendarRabbit/backend/ent/predicate"
)

// GoogleConnectionUpdate is the builder for updating GoogleConnection entities.
type GoogleConnectionUpdate struct {
	config
	hooks    []Hook
	mutation *GoogleConnectionMutation
}

// Where appends a list predicates to the GoogleConnectionUpdate builder.
func (_u *GoogleConnectionUpdate) Where(ps ...predicate.GoogleConnection) *GoogleConnectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *GoogleConnectionUpdate) SetRefreshToken(v string) *GoogleConnectionUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *GoogleConnectionUpdate) SetNillableRefreshToken(v *string) *GoogleConnectionUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *GoogleConnectionUpdate) SetAccessToken(v string) *GoogleConnectionUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *GoogleConnectionUpdate) SetNillableAccessToken(v *string) *GoogleConnectionUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// SetTokenExpiry sets the "token_expiry" field.
func (_u *GoogleConnectionUpdate) SetTokenExpiry(v time.Time) *GoogleConnectionUpdate {
	_u.mutation.SetTokenExpiry(v)
	return _u
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_u *GoogleConnectionUpdate) SetNillableTokenExpiry(v *time.Time) *GoogleConnectionUpdate {
	if v != nil {
		_u.SetTokenExpiry(*v)
	}
	return _u
}

// ClearTokenExpiry clears the value of the "token_expiry" field.
func (_u *GoogleConnectionUpdate) ClearTokenExpiry() *GoogleConnectionUpdate {
	_u.mutation.ClearTokenExpiry()
	return _u
}

// SetCalendarID sets the "calendar_id" field.
func (_u *GoogleConnectionUpdate) SetCalendarID(v string) *GoogleConnectionUpdate {
	_u.mutation.SetCalendarID(v)
	return _u
}

// SetNillableCalendarID sets the "calendar_id" field if the given value is not nil.
func (_u *GoogleConnectionUpdate) SetNillableCalendarID(v *string) *GoogleConnectionUpdate {
	if v != nil {
		_u.SetCalendarID(*v)
	}
	return _u
}

// SetConnected sets the "connected" field.
func (_u *GoogleConnectionUpdate) SetConnected(v bool) *GoogleConnectionUpdate {
	_u.mutation.SetConnected(v)
	return _u
}

// SetNillableConnected sets the "connected" field if the given value is not nil.
func (_u *GoogleConnectionUpdate) SetNillableConnected(v *bool) *GoogleConnectionUpdate {
	if v != nil {
		_u.SetConnected(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GoogleConnectionUpdate) SetUpdatedAt(v time.Time) *GoogleConnectionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GoogleConnectionMutation object of the builder.
func (_u *GoogleConnectionUpdate) Mutation() *GoogleConnectionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GoogleConnectionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoogleConnectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GoogleConnectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoogleConnectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GoogleConnectionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := googleconnection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GoogleConnectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(googleconnection.Table, googleconnection.Columns, sqlgraph.NewFieldSpec(googleconnection.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(googleconnection.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(googleconnection.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenExpiry(); ok {
		_spec.SetField(googleconnection.FieldTokenExpiry, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiryCleared() {
		_spec.ClearField(googleconnection.FieldTokenExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.CalendarID(); ok {
		_spec.SetField(googleconnection.FieldCalendarID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Connected(); ok {
		_spec.SetField(googleconnection.FieldConnected, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(googleconnection.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{googleconnection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GoogleConnectionUpdateOne is the builder for updating a single GoogleConnection entity.
type GoogleConnectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GoogleConnectionMutation
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *GoogleConnectionUpdateOne) SetRefreshToken(v string) *GoogleConnectionUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *GoogleConnectionUpdateOne) SetNillableRefreshToken(v *string) *GoogleConnectionUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *GoogleConnectionUpdateOne) SetAccessToken(v string) *GoogleConnectionUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *GoogleConnectionUpdateOne) SetNillableAccessToken(v *string) *GoogleConnectionUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// SetTokenExpiry sets the "token_expiry" field.
func (_u *GoogleConnectionUpdateOne) SetTokenExpiry(v time.Time) *GoogleConnectionUpdateOne {
	_u.mutation.SetTokenExpiry(v)
	return _u
}

// SetNillableTokenExpiry sets the "token_expiry" field if the given value is not nil.
func (_u *GoogleConnectionUpdateOne) SetNillableTokenExpiry(v *time.Time) *GoogleConnectionUpdateOne {
	if v != nil {
		_u.SetTokenExpiry(*v)
	}
	return _u
}

// ClearTokenExpiry clears the value of the "token_expiry" field.
func (_u *GoogleConnectionUpdateOne) ClearTokenExpiry() *GoogleConnectionUpdateOne {
	_u.mutation.ClearTokenExpiry()
	return _u
}

// SetCalendarID sets the "calendar_id" field.
func (_u *GoogleConnectionUpdateOne) SetCalendarID(v string) *GoogleConnectionUpdateOne {
	_u.mutation.SetCalendarID(v)
	return _u
}

// SetNillableCalendarID sets the "calendar_id" field if the given value is not nil.
func (_u *GoogleConnectionUpdateOne) SetNillableCalendarID(v *string) *GoogleConnectionUpdateOne {
	if v != nil {
		_u.SetCalendarID(*v)
	}
	return _u
}

// SetConnected sets the "connected" field.
func (_u *GoogleConnectionUpdateOne) SetConnected(v bool) *GoogleConnectionUpdateOne {
	_u.mutation.SetConnected(v)
	return _u
}

// SetNillableConnected sets the "connected" field if the given value is not nil.
func (_u *GoogleConnectionUpdateOne) SetNillableConnected(v *bool) *GoogleConnectionUpdateOne {
	if v != nil {
		_u.SetConnected(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GoogleConnectionUpdateOne) SetUpdatedAt(v time.Time) *GoogleConnectionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GoogleConnectionMutation object of the builder.
func (_u *GoogleConnectionUpdateOne) Mutation() *GoogleConnectionMutation {
	return _u.mutation
}

// Where appends a list predicates to the GoogleConnectionUpdate builder.
func (_u *GoogleConnectionUpdateOne) Where(ps ...predicate.GoogleConnection) *GoogleConnectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GoogleConnectionUpdateOne) Select(field string, fields ...string) *GoogleConnectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GoogleConnection entity.
func (_u *GoogleConnectionUpdateOne) Save(ctx context.Context) (*GoogleConnection, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoogleConnectionUpdateOne) SaveX(ctx context.Context) *GoogleConnection {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GoogleConnectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoogleConnectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GoogleConnectionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := googleconnection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GoogleConnectionUpdateOne) sqlSave(ctx context.Context) (_node *GoogleConnection, err error) {
	_spec := sqlgraph.NewUpdateSpec(googleconnection.Table, googleconnection.Columns, sqlgraph.NewFieldSpec(googleconnection.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GoogleConnection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, googleconnection.FieldID)
		for _, f := range fields {
			if !googleconnection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != googleconnection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(googleconnection.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(googleconnection.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenExpiry(); ok {
		_spec.SetField(googleconnection.FieldTokenExpiry, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiryCleared() {
		_spec.ClearField(googleconnection.FieldTokenExpiry, field.TypeTime)
	}
	if value, ok := _u.mutation.CalendarID(); ok {
		_spec.SetField(googleconnection.FieldCalendarID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Connected(); ok {
		_spec.SetField(googleconnection.FieldConnected, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(googleconnection.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GoogleConnection{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{googleconnection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
