// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ITK13201/CalendarRabbit/backend/ent/googleconnection"
)

// GoogleConnection is the model entity for the GoogleConnection schema.
type GoogleConnection struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken string `json:"refresh_token,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken string `json:"access_token,omitempty"`
	// TokenExpiry holds the value of the "token_expiry" field.
	TokenExpiry time.Time `json:"token_expiry,omitempty"`
	// CalendarID holds the value of the "calendar_id" field.
	CalendarID string `json:"calendar_id,omitempty"`
	// Connected holds the value of the "connected" field.
	Connected bool `json:"connected,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GoogleConnection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case googleconnection.FieldConnected:
			values[i] = new(sql.NullBool)
		case googleconnection.FieldID:
			values[i] = new(sql.NullInt64)
		case googleconnection.FieldRefreshToken, googleconnection.FieldAccessToken, googleconnection.FieldCalendarID:
			values[i] = new(sql.NullString)
		case googleconnection.FieldTokenExpiry, googleconnection.FieldCreatedAt, googleconnection.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GoogleConnection fields.
func (_m *GoogleConnection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case googleconnection.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case googleconnection.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				_m.RefreshToken = value.String
			}
		case googleconnection.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				_m.AccessToken = value.String
			}
		case googleconnection.FieldTokenExpiry:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field token_expiry", values[i])
			} else if value.Valid {
				_m.TokenExpiry = value.Time
			}
		case googleconnection.FieldCalendarID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field calendar_id", values[i])
			} else if value.Valid {
				_m.CalendarID = value.String
			}
		case googleconnection.FieldConnected:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field connected", values[i])
			} else if value.Valid {
				_m.Connected = value.Bool
			}
		case googleconnection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case googleconnection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GoogleConnection.
// This includes values selected through modifiers, order, etc.
func (_m *GoogleConnection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GoogleConnection.
// Note that you need to call GoogleConnection.Unwrap() before calling this method if this GoogleConnection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GoogleConnection) Update() *GoogleConnectionUpdateOne {
	return NewGoogleConnectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GoogleConnection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GoogleConnection) Unwrap() *GoogleConnection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GoogleConnection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GoogleConnection) String() string {
	var builder strings.Builder
	builder.WriteString("GoogleConnection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("refresh_token=")
	builder.WriteString(_m.RefreshToken)
	builder.WriteString(", ")
	builder.WriteString("access_token=")
	builder.WriteString(_m.AccessToken)
	builder.WriteString(", ")
	builder.WriteString("token_expiry=")
	builder.WriteString(_m.TokenExpiry.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("calendar_id=")
	builder.WriteString(_m.CalendarID)
	builder.WriteString(", ")
	builder.WriteString("connected=")
	builder.WriteString(fmt.Sprintf("%v", _m.Connected))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GoogleConnections is a parsable slice of GoogleConnection.
type GoogleConnections []*GoogleConnection
