// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ITK13201/CalendarRabbit/backend/ent/appsetting"
	"github.com/ITK13201/CalendarRabbit/backend/ent/calendarevent"
	"github.com/ITK13201/CalendarRabbit/backend/ent/conversation"
	"github.com/ITK13201/CalendarRabbit/backend/ent/eventproposal"
	"github.com/ITK13201/CalendarRabbit/backend/ent/message"
	"github.com/ITK13201/CalendarRabbit/backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appsettingFields := schema.AppSetting{}.Fields()
	_ = appsettingFields
	// appsettingDescTimezone is the schema descriptor for timezone field.
	appsettingDescTimezone := appsettingFields[0].Descriptor()
	// appsetting.DefaultTimezone holds the default value on creation for the timezone field.
	appsetting.DefaultTimezone = appsettingDescTimezone.Default.(string)
	// appsetting.TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	appsetting.TimezoneValidator = appsettingDescTimezone.Validators[0].(func(string) error)
	// appsettingDescUpdatedAt is the schema descriptor for updated_at field.
	appsettingDescUpdatedAt := appsettingFields[2].Descriptor()
	// appsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appsetting.DefaultUpdatedAt = appsettingDescUpdatedAt.Default.(func() time.Time)
	// appsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appsetting.UpdateDefaultUpdatedAt = appsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	calendareventFields := schema.CalendarEvent{}.Fields()
	_ = calendareventFields
	// calendareventDescTitle is the schema descriptor for title field.
	calendareventDescTitle := calendareventFields[0].Descriptor()
	// calendarevent.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	calendarevent.TitleValidator = calendareventDescTitle.Validators[0].(func(string) error)
	// calendareventDescAllDay is the schema descriptor for all_day field.
	calendareventDescAllDay := calendareventFields[3].Descriptor()
	// calendarevent.DefaultAllDay holds the default value on creation for the all_day field.
	calendarevent.DefaultAllDay = calendareventDescAllDay.Default.(bool)
	// calendareventDescLocation is the schema descriptor for location field.
	calendareventDescLocation := calendareventFields[4].Descriptor()
	// calendarevent.DefaultLocation holds the default value on creation for the location field.
	calendarevent.DefaultLocation = calendareventDescLocation.Default.(string)
	// calendareventDescDescription is the schema descriptor for description field.
	calendareventDescDescription := calendareventFields[5].Descriptor()
	// calendarevent.DefaultDescription holds the default value on creation for the description field.
	calendarevent.DefaultDescription = calendareventDescDescription.Default.(string)
	// calendareventDescSourceURL is the schema descriptor for source_url field.
	calendareventDescSourceURL := calendareventFields[6].Descriptor()
	// calendarevent.DefaultSourceURL holds the default value on creation for the source_url field.
	calendarevent.DefaultSourceURL = calendareventDescSourceURL.Default.(string)
	// calendareventDescCreatedAt is the schema descriptor for created_at field.
	calendareventDescCreatedAt := calendareventFields[7].Descriptor()
	// calendarevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	calendarevent.DefaultCreatedAt = calendareventDescCreatedAt.Default.(func() time.Time)
	// calendareventDescUpdatedAt is the schema descriptor for updated_at field.
	calendareventDescUpdatedAt := calendareventFields[8].Descriptor()
	// calendarevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	calendarevent.DefaultUpdatedAt = calendareventDescUpdatedAt.Default.(func() time.Time)
	// calendarevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	calendarevent.UpdateDefaultUpdatedAt = calendareventDescUpdatedAt.UpdateDefault.(func() time.Time)
	conversationFields := schema.Conversation{}.Fields()
	_ = conversationFields
	// conversationDescCreatedAt is the schema descriptor for created_at field.
	conversationDescCreatedAt := conversationFields[0].Descriptor()
	// conversation.DefaultCreatedAt holds the default value on creation for the created_at field.
	conversation.DefaultCreatedAt = conversationDescCreatedAt.Default.(func() time.Time)
	// conversationDescUpdatedAt is the schema descriptor for updated_at field.
	conversationDescUpdatedAt := conversationFields[1].Descriptor()
	// conversation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	conversation.DefaultUpdatedAt = conversationDescUpdatedAt.Default.(func() time.Time)
	// conversation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	conversation.UpdateDefaultUpdatedAt = conversationDescUpdatedAt.UpdateDefault.(func() time.Time)
	eventproposalFields := schema.EventProposal{}.Fields()
	_ = eventproposalFields
	// eventproposalDescTitle is the schema descriptor for title field.
	eventproposalDescTitle := eventproposalFields[0].Descriptor()
	// eventproposal.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	eventproposal.TitleValidator = eventproposalDescTitle.Validators[0].(func(string) error)
	// eventproposalDescAllDay is the schema descriptor for all_day field.
	eventproposalDescAllDay := eventproposalFields[3].Descriptor()
	// eventproposal.DefaultAllDay holds the default value on creation for the all_day field.
	eventproposal.DefaultAllDay = eventproposalDescAllDay.Default.(bool)
	// eventproposalDescLocation is the schema descriptor for location field.
	eventproposalDescLocation := eventproposalFields[4].Descriptor()
	// eventproposal.DefaultLocation holds the default value on creation for the location field.
	eventproposal.DefaultLocation = eventproposalDescLocation.Default.(string)
	// eventproposalDescDescription is the schema descriptor for description field.
	eventproposalDescDescription := eventproposalFields[5].Descriptor()
	// eventproposal.DefaultDescription holds the default value on creation for the description field.
	eventproposal.DefaultDescription = eventproposalDescDescription.Default.(string)
	// eventproposalDescSourceURL is the schema descriptor for source_url field.
	eventproposalDescSourceURL := eventproposalFields[6].Descriptor()
	// eventproposal.DefaultSourceURL holds the default value on creation for the source_url field.
	eventproposal.DefaultSourceURL = eventproposalDescSourceURL.Default.(string)
	// eventproposalDescCreatedAt is the schema descriptor for created_at field.
	eventproposalDescCreatedAt := eventproposalFields[8].Descriptor()
	// eventproposal.DefaultCreatedAt holds the default value on creation for the created_at field.
	eventproposal.DefaultCreatedAt = eventproposalDescCreatedAt.Default.(func() time.Time)
	// eventproposalDescUpdatedAt is the schema descriptor for updated_at field.
	eventproposalDescUpdatedAt := eventproposalFields[9].Descriptor()
	// eventproposal.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	eventproposal.DefaultUpdatedAt = eventproposalDescUpdatedAt.Default.(func() time.Time)
	// eventproposal.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	eventproposal.UpdateDefaultUpdatedAt = eventproposalDescUpdatedAt.UpdateDefault.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[2].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
}
