// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppSettingsColumns holds the columns for the "app_settings" table.
	AppSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "timezone", Type: field.TypeString, Default: "Asia/Tokyo"},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AppSettingsTable holds the schema information for the "app_settings" table.
	AppSettingsTable = &schema.Table{
		Name:       "app_settings",
		Columns:    AppSettingsColumns,
		PrimaryKey: []*schema.Column{AppSettingsColumns[0]},
	}
	// CalendarEventsColumns holds the columns for the "calendar_events" table.
	CalendarEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "starts_at", Type: field.TypeTime},
		{Name: "ends_at", Type: field.TypeTime},
		{Name: "all_day", Type: field.TypeBool, Default: false},
		{Name: "location", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "source_url", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CalendarEventsTable holds the schema information for the "calendar_events" table.
	CalendarEventsTable = &schema.Table{
		Name:       "calendar_events",
		Columns:    CalendarEventsColumns,
		PrimaryKey: []*schema.Column{CalendarEventsColumns[0]},
	}
	// ConversationsColumns holds the columns for the "conversations" table.
	ConversationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ConversationsTable holds the schema information for the "conversations" table.
	ConversationsTable = &schema.Table{
		Name:       "conversations",
		Columns:    ConversationsColumns,
		PrimaryKey: []*schema.Column{ConversationsColumns[0]},
	}
	// EventProposalsColumns holds the columns for the "event_proposals" table.
	EventProposalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "starts_at", Type: field.TypeTime},
		{Name: "ends_at", Type: field.TypeTime},
		{Name: "all_day", Type: field.TypeBool, Default: false},
		{Name: "location", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "source_url", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "approved", "rejected"}, Default: "pending"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "conversation_proposals", Type: field.TypeInt},
		{Name: "event_proposal_calendar_event", Type: field.TypeInt, Nullable: true},
		{Name: "message_proposals", Type: field.TypeInt, Nullable: true},
	}
	// EventProposalsTable holds the schema information for the "event_proposals" table.
	EventProposalsTable = &schema.Table{
		Name:       "event_proposals",
		Columns:    EventProposalsColumns,
		PrimaryKey: []*schema.Column{EventProposalsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "event_proposals_conversations_proposals",
				Columns:    []*schema.Column{EventProposalsColumns[11]},
				RefColumns: []*schema.Column{ConversationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "event_proposals_calendar_events_calendar_event",
				Columns:    []*schema.Column{EventProposalsColumns[12]},
				RefColumns: []*schema.Column{CalendarEventsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "event_proposals_messages_proposals",
				Columns:    []*schema.Column{EventProposalsColumns[13]},
				RefColumns: []*schema.Column{MessagesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"user", "assistant"}},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "conversation_messages", Type: field.TypeInt},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "messages_conversations_messages",
				Columns:    []*schema.Column{MessagesColumns[4]},
				RefColumns: []*schema.Column{ConversationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppSettingsTable,
		CalendarEventsTable,
		ConversationsTable,
		EventProposalsTable,
		MessagesTable,
	}
)

func init() {
	EventProposalsTable.ForeignKeys[0].RefTable = ConversationsTable
	EventProposalsTable.ForeignKeys[1].RefTable = CalendarEventsTable
	EventProposalsTable.ForeignKeys[2].RefTable = MessagesTable
	MessagesTable.ForeignKeys[0].RefTable = ConversationsTable
}
