// Code generated by ent, DO NOT EDIT.

package calendarevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the calendarevent type in the database.
	Label = "calendar_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldEndsAt holds the string denoting the ends_at field in the database.
	FieldEndsAt = "ends_at"
	// FieldAllDay holds the string denoting the all_day field in the database.
	FieldAllDay = "all_day"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSourceURL holds the string denoting the source_url field in the database.
	FieldSourceURL = "source_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProposal holds the string denoting the proposal edge name in mutations.
	EdgeProposal = "proposal"
	// Table holds the table name of the calendarevent in the database.
	Table = "calendar_events"
	// ProposalTable is the table that holds the proposal relation/edge.
	ProposalTable = "event_proposals"
	// ProposalInverseTable is the table name for the EventProposal entity.
	// It exists in this package in order to avoid circular dependency with the "eventproposal" package.
	ProposalInverseTable = "event_proposals"
	// ProposalColumn is the table column denoting the proposal relation/edge.
	ProposalColumn = "event_proposal_calendar_event"
)

// Columns holds all SQL columns for calendarevent fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldStartsAt,
	FieldEndsAt,
	FieldAllDay,
	FieldLocation,
	FieldDescription,
	FieldSourceURL,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultAllDay holds the default value on creation for the "all_day" field.
	DefaultAllDay bool
	// DefaultLocation holds the default value on creation for the "location" field.
	DefaultLocation string
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultSourceURL holds the default value on creation for the "source_url" field.
	DefaultSourceURL string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CalendarEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByEndsAt orders the results by the ends_at field.
func ByEndsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndsAt, opts...).ToFunc()
}

// ByAllDay orders the results by the all_day field.
func ByAllDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllDay, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySourceURL orders the results by the source_url field.
func BySourceURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProposalCount orders the results by proposal count.
func ByProposalCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProposalStep(), opts...)
	}
}

// ByProposal orders the results by proposal terms.
func ByProposal(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProposalStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProposalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProposalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ProposalTable, ProposalColumn),
	)
}
