// Code generated by ent, DO NOT EDIT.

package appsetting

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the appsetting type in the database.
	Label = "app_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldLlmProvider holds the string denoting the llm_provider field in the database.
	FieldLlmProvider = "llm_provider"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the appsetting in the database.
	Table = "app_settings"
)

// Columns holds all SQL columns for appsetting fields.
var Columns = []string{
	FieldID,
	FieldTimezone,
	FieldLlmProvider,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTimezone holds the default value on creation for the "timezone" field.
	DefaultTimezone string
	// TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	TimezoneValidator func(string) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// LlmProvider defines the type for the "llm_provider" enum field.
type LlmProvider string

// LlmProviderDeepseek is the default value of the LlmProvider enum.
const DefaultLlmProvider = LlmProviderDeepseek

// LlmProvider values.
const (
	LlmProviderDeepseek LlmProvider = "deepseek"
	LlmProviderClaude   LlmProvider = "claude"
)

func (lp LlmProvider) String() string {
	return string(lp)
}

// LlmProviderValidator is a validator for the "llm_provider" field enum values. It is called by the builders before save.
func LlmProviderValidator(lp LlmProvider) error {
	switch lp {
	case LlmProviderDeepseek, LlmProviderClaude:
		return nil
	default:
		return fmt.Errorf("appsetting: invalid enum value for llm_provider field: %q", lp)
	}
}

// OrderOption defines the ordering options for the AppSetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByLlmProvider orders the results by the llm_provider field.
func ByLlmProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLlmProvider, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
