// Code generated by ent, DO NOT EDIT.

package appsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ITK13201/CalendarRabbit/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldID, id))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldTimezone, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldContainsFold(FieldTimezone, v))
}

// LlmProviderEQ applies the EQ predicate on the "llm_provider" field.
func LlmProviderEQ(v LlmProvider) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldLlmProvider, v))
}

// LlmProviderNEQ applies the NEQ predicate on the "llm_provider" field.
func LlmProviderNEQ(v LlmProvider) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldLlmProvider, v))
}

// LlmProviderIn applies the In predicate on the "llm_provider" field.
func LlmProviderIn(vs ...LlmProvider) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldLlmProvider, vs...))
}

// LlmProviderNotIn applies the NotIn predicate on the "llm_provider" field.
func LlmProviderNotIn(vs ...LlmProvider) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldLlmProvider, vs...))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppSetting {
	return predicate.AppSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppSetting) predicate.AppSetting {
	return predicate.AppSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppSetting) predicate.AppSetting {
	return predicate.AppSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppSetting) predicate.AppSetting {
	return predicate.AppSetting(sql.NotPredicates(p))
}
